// Generated by scripts/sync-shared-lib.js — edit the citizen-app copy, not this one.
import type { Dictionary } from "../translate";

/** Assamese. MACHINE-TRANSLATED, NOT REVIEWED. Check the SOS and severity lines first. */
export const as: Dictionary = {
  Home: "ঘৰ",
  Report: "প্ৰতিবেদন",
  Alerts: "সতৰ্কবাণী",
  Shelter: "আশ্ৰয়",
  Mine: "মোৰ",
  Help: "সহায়",
  Dashboard: "ডেশ্বব’ৰ্ড",
  "Live Alerts": "প্ৰত্যক্ষ সতৰ্কবাণী",
  "Find Shelter": "আশ্ৰয় বিচাৰক",
  "My Reports": "মোৰ প্ৰতিবেদন",
  "Emergency Contacts": "জৰুৰীকালীন যোগাযোগ",
  "Report an Incident": "ঘটনাৰ খবৰ দিয়ক",

  "Alerts, shelters and teams nearest to where you are":
    "আপোনাৰ আটাইতকৈ ওচৰৰ সতৰ্কবাণী, আশ্ৰয়স্থল আৰু দল",
  "Photo, location, severity — filed in under a minute":
    "ফটো, ঠাই, গুৰুত্ব — এক মিনিটতকৈ কম সময়ত দাখিল",
  "Official warnings within {km} km of you": "আপোনাৰ পৰা {km} কি.মি.ৰ ভিতৰত চৰকাৰী সতৰ্কবাণী",
  "Track the status of what you have reported": "আপুনি জনোৱা কথাৰ অৱস্থা চাওক",
  "Tap any number to call directly": "পোনপটীয়াকৈ ফোন কৰিবলৈ যিকোনো নম্বৰত টিপক",
  "Shelters, teams and supply points on the map": "মানচিত্ৰত আশ্ৰয়স্থল, দল আৰু যোগান কেন্দ্ৰ",
  "Nearest open shelter: {name}, {km} km": "ওচৰৰ খোলা আশ্ৰয়স্থল: {name}, {km} কি.মি.",

  "SOS — hold to send": "এছঅ’এছ — পঠিয়াবলৈ টিপি ৰাখক",
  "Keep holding…": "টিপি ৰাখক…",
  "Sending…": "পঠিওৱা হৈছে…",
  "Send an SOS": "এছঅ’এছ পঠিয়াওক",
  "Press and hold for just over a second to file a critical report at your location":
    "আপোনাৰ ঠাইৰ পৰা জৰুৰী প্ৰতিবেদন দাখিল কৰিবলৈ এক ছেকেণ্ডতকৈ অলপ বেছি টিপি ৰাখক",
  "Files a critical report at your location. No description needed.":
    "আপোনাৰ ঠাইৰ পৰা জৰুৰী প্ৰতিবেদন দাখিল কৰে। বিৱৰণৰ প্ৰয়োজন নাই।",
  "Set your location below before sending an SOS.":
    "এছঅ’এছ পঠিওৱাৰ আগতে তলত আপোনাৰ ঠাই নিৰ্ধাৰণ কৰক।",
  "SOS sent": "এছঅ’এছ পঠিওৱা হ’ল",
  "SOS saved offline": "এছঅ’এছ অফলাইনত ৰখা হ’ল",
  "SOS could not be saved": "এছঅ’এছ ৰাখিব পৰা নগ’ল",
  "Try again, or call 112.": "আকৌ চেষ্টা কৰক, বা ১১২ত ফোন কৰক।",
  "Authorities have been notified of your location.":
    "কৰ্তৃপক্ষক আপোনাৰ ঠাইৰ বিষয়ে জনোৱা হৈছে।",
  "No connection right now. It will send automatically when you are back online. If you can, call 112.":
    "এতিয়া কোনো সংযোগ নাই। আপুনি অনলাইনলৈ ঘূৰি অহাৰ লগে লগে ই নিজেই পঠিওৱা হ’ব। পাৰিলে ১১২ত ফোন কৰক।",

  Location: "ঠাই",
  Severity: "গুৰুত্ব",
  Description: "বিৱৰণ",
  "Photo (optional)": "ফটো (ঐচ্ছিক)",
  "Take a photo": "ফটো তোলক",
  "Choose existing": "আগৰটো বাছক",
  "Submit Report": "প্ৰতিবেদন পঠিয়াওক",
  "What's happening? Who's affected?": "কি হৈ আছে? কোন ক্ষতিগ্ৰস্ত?",
  "Location required": "ঠাই প্ৰয়োজন",
  "Tag your location before submitting.": "পঠিওৱাৰ আগতে আপোনাৰ ঠাই দিয়ক।",
  "Report submitted": "প্ৰতিবেদন পঠিওৱা হ’ল",
  "Authorities have been notified.": "কৰ্তৃপক্ষক জনোৱা হৈছে।",
  "Authorities have been notified. Your photo could not be uploaded.":
    "কৰ্তৃপক্ষক জনোৱা হৈছে। আপোনাৰ ফটো আপল’ড কৰিব পৰা নগ’ল।",
  "Could not save your report": "আপোনাৰ প্ৰতিবেদন ৰাখিব পৰা নগ’ল",
  "Please try again.": "অনুগ্ৰহ কৰি আকৌ চেষ্টা কৰক।",
  "Camera permission needed": "কেমেৰাৰ অনুমতি লাগিব",
  "Allow camera access to photograph the incident, or choose an existing photo instead.":
    "ঘটনাৰ ফটো তুলিবলৈ কেমেৰাৰ অনুমতি দিয়ক, বা তাৰ সলনি আগৰ কোনো ফটো বাছক।",
  "Photo permission needed": "ফটোৰ অনুমতি লাগিব",
  "Enable photo access to attach an image.": "ছবি সংলগ্ন কৰিবলৈ ফটোৰ অনুমতি অন কৰক।",

  "Saved offline": "অফলাইনত ৰখা হ’ল",
  "No connection right now. Your report is saved and will be sent automatically when you're back online.":
    "এতিয়া কোনো সংযোগ নাই। আপোনাৰ প্ৰতিবেদন ৰখা হৈছে আৰু অনলাইনলৈ ঘূৰি অহাৰ লগে লগে নিজেই পঠিওৱা হ’ব।",
  "1 report waiting to send": "১টা প্ৰতিবেদন পঠিয়াবলৈ বাকী আছে",
  "{count} reports waiting to send": "{count}টা প্ৰতিবেদন পঠিয়াবলৈ বাকী আছে",
  "Saved on this device. They'll upload automatically once you're back online.":
    "এই যন্ত্ৰত ৰখা হৈছে। অনলাইনলৈ ঘূৰি অহাৰ লগে লগে নিজেই আপল’ড হ’ব।",
  "Send by SMS instead": "তাৰ সলনি এছএমএছেৰে পঠিয়াওক",
  "Opens your messages app. Works without mobile data.":
    "আপোনাৰ বাৰ্তা এপ খোলে। ম’বাইল ডাটা নোহোৱাকৈ কাম কৰে।",
  "Send the oldest waiting report as a text message":
    "বাকী থকা আটাইতকৈ পুৰণি প্ৰতিবেদন বাৰ্তা হিচাপে পঠিয়াওক",
  "Could not open messages": "বাৰ্তা এপ খুলিব পৰা নগ’ল",
  "Open your messages app and send this to the Aapda Mitra number:":
    "আপোনাৰ বাৰ্তা এপ খুলি এইটো আপদা মিত্ৰ নম্বৰলৈ পঠিয়াওক:",

  "Your position": "আপোনাৰ অৱস্থান",
  "Finding your location…": "আপোনাৰ ঠাই বিচাৰি থকা হৈছে…",
  "Use my location": "মোৰ ঠাই ব্যৱহাৰ কৰক",
  "Update location": "ঠাই আপডেট কৰক",
  "Name my place": "মোৰ ঠাইৰ নাম দিয়ক",
  "Where are you?": "আপুনি ক’ত আছে?",
  State: "ৰাজ্য",
  District: "জিলা",
  "Town or city": "চহৰ বা নগৰ",
  "No town is listed here": "ইয়াত কোনো চহৰ তালিকাভুক্ত হোৱা নাই",
  "Search {towns} towns, {districts} districts": "{towns} চহৰ, {districts} জিলাত বিচাৰক",
  "Filter {n} towns": "{n} চহৰ বাছনি কৰক",
  approximate: "আনুমানিক",
  "approximate, set by hand": "আনুমানিক, হাতেৰে দিয়া",
  "Location access is turned off for this app. Allow it in Settings, or name your place below.":
    "এই এপৰ বাবে ঠাইৰ অনুমতি বন্ধ আছে। ছেটিংছত ইয়াক দিয়ক, বা তলত আপোনাৰ ঠাইৰ নাম দিয়ক।",
  "Location Services is switched off on this device. Turn it on, or name your place below.":
    "এই যন্ত্ৰত ল’কেচন সেৱা বন্ধ আছে। ইয়াক অন কৰক, বা তলত আপোনাৰ ঠাইৰ নাম দিয়ক।",
  "Your device didn't return a location in time. Moving outdoors often helps.":
    "আপোনাৰ যন্ত্ৰই সময়মতে ঠাই দিয়া নাই। বাহিৰলৈ ওলাই গ’লে সঘনাই সহায় হয়।",
  "Location lookup failed. You can name your place instead.":
    "ঠাই বিচাৰি পোৱা নগ’ল। তাৰ সলনি আপুনি নিজৰ ঠাইৰ নাম দিব পাৰে।",

  "Active alerts within {km} km": "{km} কি.মি.ৰ ভিতৰত সক্ৰিয় সতৰ্কবাণী",
  "Most severe: {type}{agency} · {km} away": "আটাইতকৈ গুৰুতৰ: {type}{agency} · {km} দূৰত",
  "No official warnings currently cover your area.":
    "এতিয়া আপোনাৰ অঞ্চলৰ বাবে কোনো চৰকাৰী সতৰ্কবাণী নাই।",
  "Nearest available shelter": "ওচৰৰ উপলব্ধ আশ্ৰয়স্থল",
  "No shelter is currently marked available in the registry.":
    "এতিয়া পঞ্জীয়নত কোনো আশ্ৰয়স্থল উপলব্ধ বুলি দেখুওৱা হোৱা নাই।",
  "Nearest available rescue team": "ওচৰৰ উপলব্ধ উদ্ধাৰ দল",
  "No rescue team is currently marked available.":
    "এতিয়া কোনো উদ্ধাৰ দল উপলব্ধ বুলি দেখুওৱা হোৱা নাই।",
  "Your open reports": "আপোনাৰ বাকী থকা প্ৰতিবেদন",
  "Still being worked. Track them under My Reports.":
    "এতিয়াও কাম চলি আছে। মোৰ প্ৰতিবেদনত সেইবোৰ চাওক।",
  "Nothing outstanding from you right now.": "এতিয়া আপোনাৰ একো বাকী নাই।",
  "None listed": "একো নাই",
  "capacity {n}": "ধাৰণক্ষমতা {n}",
  "No active alerts nearby.": "ওচৰত কোনো সক্ৰিয় সতৰ্কবাণী নাই।",
  "You haven't submitted any reports yet.": "আপুনি এতিয়ালৈকে কোনো প্ৰতিবেদন পঠিওৱা নাই।",

  low: "কম",
  medium: "মজলীয়া",
  high: "বেছি",
  critical: "জৰুৰী",
  advisory: "পৰামৰ্শ",
  watch: "নিৰীক্ষণ",
  warning: "সতৰ্কবাণী",
  severe: "গুৰুতৰ",
  open: "খোলা",
  assigned: "নিযুক্ত",
  resolved: "সমাধান হৈছে",
  available: "উপলব্ধ",
  full: "ভৰি আছে",
  dispatched: "পঠিওৱা হৈছে",
  shelter: "আশ্ৰয়স্থল",
  "rescue team": "উদ্ধাৰ দল",
  "supply stock": "যোগান ভঁৰাল",
  Open: "খোলা",
  Full: "ভৰি আছে",
  "Out on a call": "কামত ওলাই গৈছে",

  "National Emergency Number": "ৰাষ্ট্ৰীয় জৰুৰীকালীন নম্বৰ",
  Police: "আৰক্ষী",
  Fire: "অগ্নিনিৰ্বাপক",
  Ambulance: "এম্বুলেন্স",
  "NDMA Disaster Management Helpline": "এনডিএমএ দুৰ্যোগ ব্যৱস্থাপনা হেল্পলাইন",
  "Women's Helpline": "মহিলা হেল্পলাইন",
  "Call {name} on {number}": "{name}ক {number}ত ফোন কৰক",

  Close: "বন্ধ কৰক",
  Change: "সলনি কৰক",
  "Change language": "ভাষা সলনি কৰক",
  "Choose your language": "আপোনাৰ ভাষা বাছক",
};
