// Generated by scripts/sync-shared-lib.js — edit the citizen-app copy, not this one.
import type { Dictionary } from "../translate";

/**
 * Hindi.
 *
 * MACHINE-TRANSLATED, NOT REVIEWED BY A NATIVE SPEAKER. Read the safety-critical
 * lines first if you are the one reviewing: the SOS strings, the offline and SMS
 * strings, and the words for severity. Getting "critical" or "hold to send"
 * subtly wrong costs more here than an awkward sentence anywhere else.
 *
 * A key with no entry falls through to the English source, so deleting a line
 * you are unsure of is always safe.
 */
export const hi: Dictionary = {
  // Screens and navigation
  Home: "होम",
  Report: "रिपोर्ट",
  Alerts: "चेतावनी",
  Shelter: "शरण",
  Mine: "मेरी",
  Help: "सहायता",
  Dashboard: "डैशबोर्ड",
  "Live Alerts": "लाइव चेतावनियाँ",
  "Find Shelter": "शरण खोजें",
  "My Reports": "मेरी रिपोर्ट",
  "Emergency Contacts": "आपातकालीन संपर्क",
  "Report an Incident": "घटना की सूचना दें",

  // Screen subtitles
  "Alerts, shelters and teams nearest to where you are":
    "आपके सबसे नज़दीक की चेतावनियाँ, शरणस्थल और टीमें",
  "Photo, location, severity — filed in under a minute":
    "फ़ोटो, स्थान, गंभीरता — एक मिनट से भी कम में दर्ज",
  "Official warnings within {km} km of you": "आपसे {km} किमी के भीतर सरकारी चेतावनियाँ",
  "Track the status of what you have reported": "आपने जो सूचना दी है उसकी स्थिति देखें",
  "Tap any number to call directly": "सीधे कॉल करने के लिए किसी भी नंबर पर टैप करें",
  "Shelters, teams and supply points on the map": "मानचित्र पर शरणस्थल, टीमें और आपूर्ति केंद्र",
  "Nearest open shelter: {name}, {km} km": "निकटतम खुला शरणस्थल: {name}, {km} किमी",

  // The SOS path — read these first
  "SOS — hold to send": "एसओएस — भेजने के लिए दबाए रखें",
  "Keep holding…": "दबाए रखें…",
  "Sending…": "भेजा जा रहा है…",
  "Send an SOS": "एसओएस भेजें",
  "Press and hold for just over a second to file a critical report at your location":
    "अपने स्थान से गंभीर रिपोर्ट दर्ज करने के लिए एक सेकंड से थोड़ा अधिक दबाए रखें",
  "Files a critical report at your location. No description needed.":
    "आपके स्थान से गंभीर रिपोर्ट दर्ज करता है। विवरण की आवश्यकता नहीं।",
  "Set your location below before sending an SOS.":
    "एसओएस भेजने से पहले नीचे अपना स्थान निर्धारित करें।",
  "SOS sent": "एसओएस भेजा गया",
  "SOS saved offline": "एसओएस ऑफ़लाइन सहेजा गया",
  "SOS could not be saved": "एसओएस सहेजा नहीं जा सका",
  "Try again, or call 112.": "फिर कोशिश करें, या 112 पर कॉल करें।",
  "Authorities have been notified of your location.":
    "अधिकारियों को आपके स्थान की सूचना दे दी गई है।",
  "No connection right now. It will send automatically when you are back online. If you can, call 112.":
    "अभी कोई कनेक्शन नहीं है। ऑनलाइन आते ही यह अपने आप भेज दी जाएगी। हो सके तो 112 पर कॉल करें।",

  // The report form
  Location: "स्थान",
  Severity: "गंभीरता",
  Description: "विवरण",
  "Photo (optional)": "फ़ोटो (वैकल्पिक)",
  "Take a photo": "फ़ोटो लें",
  "Choose existing": "मौजूदा चुनें",
  "Submit Report": "रिपोर्ट भेजें",
  "What's happening? Who's affected?": "क्या हो रहा है? कौन प्रभावित है?",
  "Location required": "स्थान आवश्यक है",
  "Tag your location before submitting.": "भेजने से पहले अपना स्थान दर्ज करें।",
  "Report submitted": "रिपोर्ट भेज दी गई",
  "Authorities have been notified.": "अधिकारियों को सूचित कर दिया गया है।",
  "Authorities have been notified. Your photo could not be uploaded.":
    "अधिकारियों को सूचित कर दिया गया है। आपकी फ़ोटो अपलोड नहीं हो सकी।",
  "Could not save your report": "आपकी रिपोर्ट सहेजी नहीं जा सकी",
  "Please try again.": "कृपया फिर कोशिश करें।",
  "Camera permission needed": "कैमरा अनुमति आवश्यक",
  "Allow camera access to photograph the incident, or choose an existing photo instead.":
    "घटना की फ़ोटो लेने के लिए कैमरा अनुमति दें, या इसके बजाय कोई मौजूदा फ़ोटो चुनें।",
  "Photo permission needed": "फ़ोटो अनुमति आवश्यक",
  "Enable photo access to attach an image.": "छवि जोड़ने के लिए फ़ोटो अनुमति चालू करें।",

  // Offline and the SMS fallback
  "Saved offline": "ऑफ़लाइन सहेजा गया",
  "No connection right now. Your report is saved and will be sent automatically when you're back online.":
    "अभी कोई कनेक्शन नहीं है। आपकी रिपोर्ट सहेज ली गई है और ऑनलाइन आते ही अपने आप भेज दी जाएगी।",
  "1 report waiting to send": "1 रिपोर्ट भेजी जानी बाकी है",
  "{count} reports waiting to send": "{count} रिपोर्ट भेजी जानी बाकी हैं",
  "Saved on this device. They'll upload automatically once you're back online.":
    "इस डिवाइस पर सहेजी गई हैं। ऑनलाइन आते ही अपने आप अपलोड हो जाएँगी।",
  "Send by SMS instead": "इसके बजाय एसएमएस से भेजें",
  "Opens your messages app. Works without mobile data.":
    "आपका संदेश ऐप खोलता है। मोबाइल डेटा के बिना काम करता है।",
  "Send the oldest waiting report as a text message":
    "सबसे पुरानी लंबित रिपोर्ट संदेश के रूप में भेजें",
  "Could not open messages": "संदेश ऐप नहीं खुल सका",
  "Open your messages app and send this to the Aapda Mitra number:":
    "अपना संदेश ऐप खोलें और यह आपदा मित्र नंबर पर भेजें:",

  // Location
  "Your position": "आपकी स्थिति",
  "Finding your location…": "आपका स्थान खोजा जा रहा है…",
  "Use my location": "मेरा स्थान इस्तेमाल करें",
  "Update location": "स्थान अपडेट करें",
  "Name my place": "अपनी जगह का नाम दें",
  "Where are you?": "आप कहाँ हैं?",
  State: "राज्य",
  District: "ज़िला",
  "Town or city": "कस्बा या शहर",
  "No town is listed here": "यहाँ कोई कस्बा सूचीबद्ध नहीं है",
  "Search {towns} towns, {districts} districts": "{towns} कस्बे, {districts} ज़िले खोजें",
  "Filter {n} towns": "{n} कस्बे छाँटें",
  approximate: "अनुमानित",
  "approximate, set by hand": "अनुमानित, हाथ से दर्ज",
  "Location access is turned off for this app. Allow it in Settings, or name your place below.":
    "इस ऐप के लिए स्थान की अनुमति बंद है। सेटिंग्स में इसे चालू करें, या नीचे अपनी जगह का नाम दें।",
  "Location Services is switched off on this device. Turn it on, or name your place below.":
    "इस डिवाइस पर स्थान सेवाएँ बंद हैं। इन्हें चालू करें, या नीचे अपनी जगह का नाम दें।",
  "Your device didn't return a location in time. Moving outdoors often helps.":
    "आपके डिवाइस ने समय पर स्थान नहीं बताया। खुले में जाने से अक्सर मदद मिलती है।",
  "Location lookup failed. You can name your place instead.":
    "स्थान का पता नहीं चल सका। आप इसके बजाय अपनी जगह का नाम दे सकते हैं।",

  // Dashboard readout
  "Active alerts within {km} km": "{km} किमी के भीतर सक्रिय चेतावनियाँ",
  "Most severe: {type}{agency} · {km} away": "सबसे गंभीर: {type}{agency} · {km} दूर",
  "No official warnings currently cover your area.":
    "फ़िलहाल आपके क्षेत्र के लिए कोई सरकारी चेतावनी नहीं है।",
  "Nearest available shelter": "निकटतम उपलब्ध शरणस्थल",
  "No shelter is currently marked available in the registry.":
    "फ़िलहाल रजिस्टर में कोई शरणस्थल उपलब्ध नहीं दिखाया गया है।",
  "Nearest available rescue team": "निकटतम उपलब्ध बचाव दल",
  "No rescue team is currently marked available.":
    "फ़िलहाल कोई बचाव दल उपलब्ध नहीं दिखाया गया है।",
  "Your open reports": "आपकी खुली रिपोर्टें",
  "Still being worked. Track them under My Reports.":
    "अभी काम चल रहा है। मेरी रिपोर्ट में इन्हें देखें।",
  "Nothing outstanding from you right now.": "अभी आपकी कोई रिपोर्ट लंबित नहीं है।",
  "None listed": "कोई नहीं",
  "capacity {n}": "क्षमता {n}",
  "No active alerts nearby.": "आस-पास कोई सक्रिय चेतावनी नहीं।",
  "You haven't submitted any reports yet.": "आपने अभी तक कोई रिपोर्ट नहीं भेजी है।",

  // Severity, status and resource words
  low: "कम",
  medium: "मध्यम",
  high: "अधिक",
  critical: "गंभीर",
  advisory: "सूचना",
  watch: "सतर्कता",
  warning: "चेतावनी",
  severe: "अति गंभीर",
  open: "खुली",
  assigned: "सौंपी गई",
  resolved: "निपटाई गई",
  available: "उपलब्ध",
  full: "भरा हुआ",
  dispatched: "भेजा गया",
  shelter: "शरणस्थल",
  "rescue team": "बचाव दल",
  "supply stock": "आपूर्ति भंडार",
  Open: "खुला",
  Full: "भरा हुआ",
  "Out on a call": "कॉल पर गया हुआ",

  // Emergency contacts
  "National Emergency Number": "राष्ट्रीय आपातकालीन नंबर",
  Police: "पुलिस",
  Fire: "अग्निशमन",
  Ambulance: "एम्बुलेंस",
  "NDMA Disaster Management Helpline": "एनडीएमए आपदा प्रबंधन हेल्पलाइन",
  "Women's Helpline": "महिला हेल्पलाइन",
  "Call {name} on {number}": "{name} को {number} पर कॉल करें",

  // Chrome
  Close: "बंद करें",
  Change: "बदलें",
  "Change language": "भाषा बदलें",
  "Choose your language": "अपनी भाषा चुनें",

  // Strings the citizen web view has and the app does not.
  "Sign out": "साइन आउट",
  "Try again": "फिर कोशिश करें",
  "Submitting…": "भेजा जा रहा है…",
  "Hide place list": "जगहों की सूची छिपाएँ",
  "Attached photo preview": "जोड़ी गई फ़ोटो का पूर्वावलोकन",
  "Search for your city or district": "अपना शहर या ज़िला खोजें",
  "Search {cities} cities, {districts} districts…": "{cities} शहर, {districts} ज़िले खोजें…",
  "Filter {n} towns…": "{n} कस्बे छाँटें…",
  "Location not available yet — allow location access and try again.":
    "स्थान अभी उपलब्ध नहीं है — स्थान की अनुमति दें और फिर कोशिश करें।",
  "Set your location first — use the readout above.":
    "पहले अपना स्थान निर्धारित करें — ऊपर दिया गया विवरण इस्तेमाल करें।",
  "Report submitted. Authorities have been notified.":
    "रिपोर्ट भेज दी गई। अधिकारियों को सूचित कर दिया गया है।",
  "Official warnings near you, updated continuously":
    "आपके पास की सरकारी चेतावनियाँ, लगातार अद्यतन",
  "Nearest shelters and resources on the map": "मानचित्र पर निकटतम शरणस्थल और संसाधन",
  "Fire, police, ambulance, disaster helplines": "अग्निशमन, पुलिस, एम्बुलेंस, आपदा हेल्पलाइन",
  "This site is blocked from using your location.":
    "इस साइट को आपका स्थान इस्तेमाल करने से रोका गया है।",
  "Allow location for this site in your browser settings, then try again — or just name your place below.":
    "अपने ब्राउज़र की सेटिंग्स में इस साइट के लिए स्थान की अनुमति दें, फिर कोशिश करें — या नीचे अपनी जगह का नाम दे दें।",
  "Your device didn't return a location in time.": "आपके डिवाइस ने समय पर स्थान नहीं बताया।",
  "Moving outdoors usually helps, or name your place below.":
    "खुले में जाने से आमतौर पर मदद मिलती है, या नीचे अपनी जगह का नाम दें।",
  "Your device couldn't determine a location.": "आपका डिवाइस स्थान तय नहीं कर सका।",
  "Common on a desktop with no GPS, and on a phone with Location Services switched off. Name your place below instead.":
    "बिना जीपीएस वाले कंप्यूटर पर और स्थान सेवाएँ बंद वाले फ़ोन पर यह आम है। इसके बजाय नीचे अपनी जगह का नाम दें।",
  "This browser doesn't support location lookup.":
    "यह ब्राउज़र स्थान का पता लगाना समर्थित नहीं करता।",
  "Name your place below instead.": "इसके बजाय नीचे अपनी जगह का नाम दें।",
  "This page is not on a secure (https) connection, so the browser will not share your location.":
    "यह पेज सुरक्षित (https) कनेक्शन पर नहीं है, इसलिए ब्राउज़र आपका स्थान साझा नहीं करेगा।",
  "Open the deployed https site, or name your place below.":
    "तैनात https साइट खोलें, या नीचे अपनी जगह का नाम दें।",
};
