// Generated by scripts/sync-shared-lib.js — edit the citizen-app copy, not this one.
import type { Dictionary } from "../translate";

import { as } from "./as";
import { bn } from "./bn";
import { gu } from "./gu";
import { hi } from "./hi";
import { kn } from "./kn";
import { mai } from "./mai";
import { ml } from "./ml";
import { mr } from "./mr";
import { or } from "./or";
import { pa } from "./pa";
import { ta } from "./ta";
import { te } from "./te";
import { ur } from "./ur";

/**
 * One dictionary per language, keyed by the English source string.
 *
 * English has no dictionary: it is the source, and every lookup that misses
 * falls through to the key itself. A language whose file is incomplete — or
 * absent entirely — shows English for the strings it lacks rather than a blank
 * or an identifier, so a partial translation is a partial improvement and never
 * a broken screen.
 *
 * Every dictionary here is machine-translated and has not been read by a native
 * speaker. Each file says so at the top and names the lines worth checking
 * first.
 */
export const DICTIONARIES: Record<string, Dictionary> = {
  hi,
  bn,
  mr,
  te,
  ta,
  gu,
  ur,
  kn,
  or,
  ml,
  pa,
  as,
  mai,
};
