// Generated by scripts/sync-shared-lib.js — edit the citizen-app copy, not this one.
import type { Dictionary } from "../translate";

/**
 * Kannada.
 *
 * MACHINE-TRANSLATED, NOT REVIEWED BY A NATIVE SPEAKER. Check the SOS strings,
 * the offline and SMS strings, and the severity words first.
 */
export const kn: Dictionary = {
  Home: "ಮುಖಪುಟ",
  Report: "ವರದಿ",
  Alerts: "ಎಚ್ಚರಿಕೆಗಳು",
  Shelter: "ಆಶ್ರಯ",
  Mine: "ನನ್ನವು",
  Help: "ಸಹಾಯ",
  Dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
  "Live Alerts": "ನೇರ ಎಚ್ಚರಿಕೆಗಳು",
  "Find Shelter": "ಆಶ್ರಯ ಹುಡುಕಿ",
  "My Reports": "ನನ್ನ ವರದಿಗಳು",
  "Emergency Contacts": "ತುರ್ತು ಸಂಪರ್ಕಗಳು",
  "Report an Incident": "ಘಟನೆಯನ್ನು ವರದಿ ಮಾಡಿ",

  "Alerts, shelters and teams nearest to where you are":
    "ನಿಮಗೆ ಅತ್ಯಂತ ಹತ್ತಿರದ ಎಚ್ಚರಿಕೆಗಳು, ಆಶ್ರಯಗಳು ಮತ್ತು ತಂಡಗಳು",
  "Photo, location, severity — filed in under a minute":
    "ಫೋಟೋ, ಸ್ಥಳ, ತೀವ್ರತೆ — ಒಂದು ನಿಮಿಷದೊಳಗೆ ದಾಖಲು",
  "Official warnings within {km} km of you": "ನಿಮ್ಮಿಂದ {km} ಕಿ.ಮೀ. ಒಳಗಿನ ಅಧಿಕೃತ ಎಚ್ಚರಿಕೆಗಳು",
  "Track the status of what you have reported": "ನೀವು ವರದಿ ಮಾಡಿದ್ದರ ಸ್ಥಿತಿಯನ್ನು ನೋಡಿ",
  "Tap any number to call directly": "ನೇರವಾಗಿ ಕರೆ ಮಾಡಲು ಯಾವುದೇ ಸಂಖ್ಯೆಯನ್ನು ಒತ್ತಿ",
  "Shelters, teams and supply points on the map":
    "ನಕ್ಷೆಯಲ್ಲಿ ಆಶ್ರಯಗಳು, ತಂಡಗಳು ಮತ್ತು ಸರಬರಾಜು ಕೇಂದ್ರಗಳು",
  "Nearest open shelter: {name}, {km} km": "ಹತ್ತಿರದ ತೆರೆದ ಆಶ್ರಯ: {name}, {km} ಕಿ.ಮೀ.",

  "SOS — hold to send": "ಎಸ್‌ಒಎಸ್ — ಕಳುಹಿಸಲು ಒತ್ತಿ ಹಿಡಿಯಿರಿ",
  "Keep holding…": "ಒತ್ತಿ ಹಿಡಿಯಿರಿ…",
  "Sending…": "ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ…",
  "Send an SOS": "ಎಸ್‌ಒಎಸ್ ಕಳುಹಿಸಿ",
  "Press and hold for just over a second to file a critical report at your location":
    "ನಿಮ್ಮ ಸ್ಥಳದಿಂದ ಗಂಭೀರ ವರದಿ ದಾಖಲಿಸಲು ಒಂದು ಸೆಕೆಂಡಿಗಿಂತ ಸ್ವಲ್ಪ ಹೆಚ್ಚು ಒತ್ತಿ ಹಿಡಿಯಿರಿ",
  "Files a critical report at your location. No description needed.":
    "ನಿಮ್ಮ ಸ್ಥಳದಿಂದ ಗಂಭೀರ ವರದಿಯನ್ನು ದಾಖಲಿಸುತ್ತದೆ. ವಿವರಣೆ ಅಗತ್ಯವಿಲ್ಲ.",
  "Set your location below before sending an SOS.":
    "ಎಸ್‌ಒಎಸ್ ಕಳುಹಿಸುವ ಮೊದಲು ಕೆಳಗೆ ನಿಮ್ಮ ಸ್ಥಳವನ್ನು ನಿಗದಿಪಡಿಸಿ.",
  "SOS sent": "ಎಸ್‌ಒಎಸ್ ಕಳುಹಿಸಲಾಗಿದೆ",
  "SOS saved offline": "ಎಸ್‌ಒಎಸ್ ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿ ಉಳಿಸಲಾಗಿದೆ",
  "SOS could not be saved": "ಎಸ್‌ಒಎಸ್ ಉಳಿಸಲಾಗಲಿಲ್ಲ",
  "Try again, or call 112.": "ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ, ಅಥವಾ 112ಕ್ಕೆ ಕರೆ ಮಾಡಿ.",
  "Authorities have been notified of your location.":
    "ಅಧಿಕಾರಿಗಳಿಗೆ ನಿಮ್ಮ ಸ್ಥಳದ ಬಗ್ಗೆ ತಿಳಿಸಲಾಗಿದೆ.",
  "No connection right now. It will send automatically when you are back online. If you can, call 112.":
    "ಈಗ ಸಂಪರ್ಕವಿಲ್ಲ. ನೀವು ಮತ್ತೆ ಆನ್‌ಲೈನ್‌ಗೆ ಬಂದಾಗ ಇದು ತಾನಾಗಿಯೇ ಕಳುಹಿಸಲ್ಪಡುತ್ತದೆ. ಸಾಧ್ಯವಾದರೆ 112ಕ್ಕೆ ಕರೆ ಮಾಡಿ.",

  Location: "ಸ್ಥಳ",
  Severity: "ತೀವ್ರತೆ",
  Description: "ವಿವರಣೆ",
  "Photo (optional)": "ಫೋಟೋ (ಐಚ್ಛಿಕ)",
  "Take a photo": "ಫೋಟೋ ತೆಗೆಯಿರಿ",
  "Choose existing": "ಇರುವುದನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  "Submit Report": "ವರದಿ ಕಳುಹಿಸಿ",
  "What's happening? Who's affected?": "ಏನಾಗುತ್ತಿದೆ? ಯಾರು ಬಾಧಿತರಾಗಿದ್ದಾರೆ?",
  "Location required": "ಸ್ಥಳ ಅಗತ್ಯವಿದೆ",
  "Tag your location before submitting.": "ಕಳುಹಿಸುವ ಮೊದಲು ನಿಮ್ಮ ಸ್ಥಳವನ್ನು ದಾಖಲಿಸಿ.",
  "Report submitted": "ವರದಿ ಕಳುಹಿಸಲಾಗಿದೆ",
  "Authorities have been notified.": "ಅಧಿಕಾರಿಗಳಿಗೆ ತಿಳಿಸಲಾಗಿದೆ.",
  "Authorities have been notified. Your photo could not be uploaded.":
    "ಅಧಿಕಾರಿಗಳಿಗೆ ತಿಳಿಸಲಾಗಿದೆ. ನಿಮ್ಮ ಫೋಟೋವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಲಾಗಲಿಲ್ಲ.",
  "Could not save your report": "ನಿಮ್ಮ ವರದಿಯನ್ನು ಉಳಿಸಲಾಗಲಿಲ್ಲ",
  "Please try again.": "ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
  "Camera permission needed": "ಕ್ಯಾಮೆರಾ ಅನುಮತಿ ಅಗತ್ಯವಿದೆ",
  "Allow camera access to photograph the incident, or choose an existing photo instead.":
    "ಘಟನೆಯ ಫೋಟೋ ತೆಗೆಯಲು ಕ್ಯಾಮೆರಾ ಅನುಮತಿ ನೀಡಿ, ಅಥವಾ ಬದಲಿಗೆ ಇರುವ ಫೋಟೋವನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
  "Photo permission needed": "ಫೋಟೋ ಅನುಮತಿ ಅಗತ್ಯವಿದೆ",
  "Enable photo access to attach an image.": "ಚಿತ್ರವನ್ನು ಲಗತ್ತಿಸಲು ಫೋಟೋ ಅನುಮತಿಯನ್ನು ಆನ್ ಮಾಡಿ.",

  "Saved offline": "ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿ ಉಳಿಸಲಾಗಿದೆ",
  "No connection right now. Your report is saved and will be sent automatically when you're back online.":
    "ಈಗ ಸಂಪರ್ಕವಿಲ್ಲ. ನಿಮ್ಮ ವರದಿ ಉಳಿಸಲಾಗಿದೆ ಮತ್ತು ನೀವು ಮತ್ತೆ ಆನ್‌ಲೈನ್‌ಗೆ ಬಂದಾಗ ತಾನಾಗಿಯೇ ಕಳುಹಿಸಲ್ಪಡುತ್ತದೆ.",
  "1 report waiting to send": "1 ವರದಿ ಕಳುಹಿಸಲು ಕಾಯುತ್ತಿದೆ",
  "{count} reports waiting to send": "{count} ವರದಿಗಳು ಕಳುಹಿಸಲು ಕಾಯುತ್ತಿವೆ",
  "Saved on this device. They'll upload automatically once you're back online.":
    "ಈ ಸಾಧನದಲ್ಲಿ ಉಳಿಸಲಾಗಿದೆ. ನೀವು ಮತ್ತೆ ಆನ್‌ಲೈನ್‌ಗೆ ಬಂದ ತಕ್ಷಣ ತಾನಾಗಿಯೇ ಅಪ್‌ಲೋಡ್ ಆಗುತ್ತವೆ.",
  "Send by SMS instead": "ಬದಲಿಗೆ ಎಸ್‌ಎಂಎಸ್ ಮೂಲಕ ಕಳುಹಿಸಿ",
  "Opens your messages app. Works without mobile data.":
    "ನಿಮ್ಮ ಸಂದೇಶ ಅಪ್ಲಿಕೇಶನ್ ತೆರೆಯುತ್ತದೆ. ಮೊಬೈಲ್ ಡೇಟಾ ಇಲ್ಲದೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ.",
  "Send the oldest waiting report as a text message":
    "ಕಾಯುತ್ತಿರುವ ಅತ್ಯಂತ ಹಳೆಯ ವರದಿಯನ್ನು ಸಂದೇಶವಾಗಿ ಕಳುಹಿಸಿ",
  "Could not open messages": "ಸಂದೇಶ ಅಪ್ಲಿಕೇಶನ್ ತೆರೆಯಲಾಗಲಿಲ್ಲ",
  "Open your messages app and send this to the Aapda Mitra number:":
    "ನಿಮ್ಮ ಸಂದೇಶ ಅಪ್ಲಿಕೇಶನ್ ತೆರೆದು ಇದನ್ನು ಆಪದ ಮಿತ್ರ ಸಂಖ್ಯೆಗೆ ಕಳುಹಿಸಿ:",

  "Your position": "ನಿಮ್ಮ ಸ್ಥಾನ",
  "Finding your location…": "ನಿಮ್ಮ ಸ್ಥಳವನ್ನು ಹುಡುಕಲಾಗುತ್ತಿದೆ…",
  "Use my location": "ನನ್ನ ಸ್ಥಳವನ್ನು ಬಳಸಿ",
  "Update location": "ಸ್ಥಳವನ್ನು ನವೀಕರಿಸಿ",
  "Name my place": "ನನ್ನ ಸ್ಥಳಕ್ಕೆ ಹೆಸರಿಸಿ",
  "Where are you?": "ನೀವು ಎಲ್ಲಿದ್ದೀರಿ?",
  State: "ರಾಜ್ಯ",
  District: "ಜಿಲ್ಲೆ",
  "Town or city": "ಪಟ್ಟಣ ಅಥವಾ ನಗರ",
  "No town is listed here": "ಇಲ್ಲಿ ಯಾವುದೇ ಪಟ್ಟಣ ಪಟ್ಟಿಯಲ್ಲಿಲ್ಲ",
  "Search {towns} towns, {districts} districts": "{towns} ಪಟ್ಟಣಗಳು, {districts} ಜಿಲ್ಲೆಗಳಲ್ಲಿ ಹುಡುಕಿ",
  "Filter {n} towns": "{n} ಪಟ್ಟಣಗಳನ್ನು ಸೋಸಿ",
  approximate: "ಅಂದಾಜು",
  "approximate, set by hand": "ಅಂದಾಜು, ಕೈಯಿಂದ ದಾಖಲಿಸಿದ್ದು",
  "Location access is turned off for this app. Allow it in Settings, or name your place below.":
    "ಈ ಅಪ್ಲಿಕೇಶನ್‌ಗೆ ಸ್ಥಳದ ಅನುಮತಿ ಆಫ್ ಆಗಿದೆ. ಸೆಟ್ಟಿಂಗ್‌ಗಳಲ್ಲಿ ಅದನ್ನು ನೀಡಿ, ಅಥವಾ ಕೆಳಗೆ ನಿಮ್ಮ ಸ್ಥಳಕ್ಕೆ ಹೆಸರಿಸಿ.",
  "Location Services is switched off on this device. Turn it on, or name your place below.":
    "ಈ ಸಾಧನದಲ್ಲಿ ಸ್ಥಳ ಸೇವೆಗಳು ಆಫ್ ಆಗಿವೆ. ಅವನ್ನು ಆನ್ ಮಾಡಿ, ಅಥವಾ ಕೆಳಗೆ ನಿಮ್ಮ ಸ್ಥಳಕ್ಕೆ ಹೆಸರಿಸಿ.",
  "Your device didn't return a location in time. Moving outdoors often helps.":
    "ನಿಮ್ಮ ಸಾಧನ ಸಮಯಕ್ಕೆ ಸ್ಥಳವನ್ನು ನೀಡಲಿಲ್ಲ. ಹೊರಗೆ ಹೋಗುವುದು ಹೆಚ್ಚಾಗಿ ಸಹಾಯ ಮಾಡುತ್ತದೆ.",
  "Location lookup failed. You can name your place instead.":
    "ಸ್ಥಳ ಪತ್ತೆ ವಿಫಲವಾಯಿತು. ಬದಲಿಗೆ ನೀವು ನಿಮ್ಮ ಸ್ಥಳಕ್ಕೆ ಹೆಸರಿಸಬಹುದು.",

  "Active alerts within {km} km": "{km} ಕಿ.ಮೀ. ಒಳಗಿನ ಸಕ್ರಿಯ ಎಚ್ಚರಿಕೆಗಳು",
  "Most severe: {type}{agency} · {km} away": "ಅತ್ಯಂತ ತೀವ್ರ: {type}{agency} · {km} ದೂರದಲ್ಲಿ",
  "No official warnings currently cover your area.":
    "ಪ್ರಸ್ತುತ ನಿಮ್ಮ ಪ್ರದೇಶಕ್ಕೆ ಯಾವುದೇ ಅಧಿಕೃತ ಎಚ್ಚರಿಕೆ ಇಲ್ಲ.",
  "Nearest available shelter": "ಹತ್ತಿರದ ಲಭ್ಯವಿರುವ ಆಶ್ರಯ",
  "No shelter is currently marked available in the registry.":
    "ಪ್ರಸ್ತುತ ನೋಂದಣಿಯಲ್ಲಿ ಯಾವುದೇ ಆಶ್ರಯ ಲಭ್ಯವೆಂದು ಗುರುತಿಸಲಾಗಿಲ್ಲ.",
  "Nearest available rescue team": "ಹತ್ತಿರದ ಲಭ್ಯವಿರುವ ರಕ್ಷಣಾ ತಂಡ",
  "No rescue team is currently marked available.":
    "ಪ್ರಸ್ತುತ ಯಾವುದೇ ರಕ್ಷಣಾ ತಂಡ ಲಭ್ಯವೆಂದು ಗುರುತಿಸಲಾಗಿಲ್ಲ.",
  "Your open reports": "ನಿಮ್ಮ ಬಾಕಿ ವರದಿಗಳು",
  "Still being worked. Track them under My Reports.":
    "ಇನ್ನೂ ಕೆಲಸ ನಡೆಯುತ್ತಿದೆ. ನನ್ನ ವರದಿಗಳಲ್ಲಿ ಅವನ್ನು ನೋಡಿ.",
  "Nothing outstanding from you right now.": "ಪ್ರಸ್ತುತ ನಿಮ್ಮಿಂದ ಏನೂ ಬಾಕಿ ಇಲ್ಲ.",
  "None listed": "ಯಾವುದೂ ಇಲ್ಲ",
  "capacity {n}": "ಸಾಮರ್ಥ್ಯ {n}",
  "No active alerts nearby.": "ಹತ್ತಿರದಲ್ಲಿ ಸಕ್ರಿಯ ಎಚ್ಚರಿಕೆಗಳಿಲ್ಲ.",
  "You haven't submitted any reports yet.": "ನೀವು ಇನ್ನೂ ಯಾವುದೇ ವರದಿ ಕಳುಹಿಸಿಲ್ಲ.",

  low: "ಕಡಿಮೆ",
  medium: "ಮಧ್ಯಮ",
  high: "ಹೆಚ್ಚು",
  critical: "ಗಂಭೀರ",
  advisory: "ಸೂಚನೆ",
  watch: "ನಿಗಾ",
  warning: "ಎಚ್ಚರಿಕೆ",
  severe: "ತೀವ್ರ",
  open: "ತೆರೆದಿದೆ",
  assigned: "ನಿಯೋಜಿಸಲಾಗಿದೆ",
  resolved: "ಪರಿಹರಿಸಲಾಗಿದೆ",
  available: "ಲಭ್ಯ",
  full: "ಭರ್ತಿ",
  dispatched: "ಕಳುಹಿಸಲಾಗಿದೆ",
  shelter: "ಆಶ್ರಯ",
  "rescue team": "ರಕ್ಷಣಾ ತಂಡ",
  "supply stock": "ಸರಬರಾಜು ದಾಸ್ತಾನು",
  Open: "ತೆರೆದಿದೆ",
  Full: "ಭರ್ತಿ",
  "Out on a call": "ಕೆಲಸಕ್ಕೆ ಹೋಗಿದೆ",

  "National Emergency Number": "ರಾಷ್ಟ್ರೀಯ ತುರ್ತು ಸಂಖ್ಯೆ",
  Police: "ಪೊಲೀಸ್",
  Fire: "ಅಗ್ನಿಶಾಮಕ",
  Ambulance: "ಆಂಬ್ಯುಲೆನ್ಸ್",
  "NDMA Disaster Management Helpline": "ಎನ್‌ಡಿಎಂಎ ವಿಪತ್ತು ನಿರ್ವಹಣೆ ಸಹಾಯವಾಣಿ",
  "Women's Helpline": "ಮಹಿಳಾ ಸಹಾಯವಾಣಿ",
  "Call {name} on {number}": "{name} ಅವರಿಗೆ {number} ಗೆ ಕರೆ ಮಾಡಿ",

  Close: "ಮುಚ್ಚಿ",
  Change: "ಬದಲಾಯಿಸಿ",
  "Change language": "ಭಾಷೆ ಬದಲಾಯಿಸಿ",
  "Choose your language": "ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",

  // Strings the citizen web view has and the app does not.
  "Sign out": "ಸೈನ್ ಔಟ್",
  "Try again": "ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ",
  "Submitting…": "ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ…",
  "Hide place list": "ಸ್ಥಳಗಳ ಪಟ್ಟಿಯನ್ನು ಮರೆಮಾಡಿ",
  "Attached photo preview": "ಲಗತ್ತಿಸಿದ ಫೋಟೋ ಮುನ್ನೋಟ",
  "Search for your city or district": "ನಿಮ್ಮ ನಗರ ಅಥವಾ ಜಿಲ್ಲೆಯನ್ನು ಹುಡುಕಿ",
  "Search {cities} cities, {districts} districts…":
    "{cities} ನಗರಗಳು, {districts} ಜಿಲ್ಲೆಗಳಲ್ಲಿ ಹುಡುಕಿ…",
  "Filter {n} towns…": "{n} ಪಟ್ಟಣಗಳನ್ನು ಸೋಸಿ…",
  "Location not available yet — allow location access and try again.":
    "ಸ್ಥಳ ಇನ್ನೂ ಲಭ್ಯವಿಲ್ಲ — ಸ್ಥಳದ ಅನುಮತಿ ನೀಡಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
  "Set your location first — use the readout above.":
    "ಮೊದಲು ನಿಮ್ಮ ಸ್ಥಳವನ್ನು ನಿಗದಿಪಡಿಸಿ — ಮೇಲಿನ ಮಾಹಿತಿಯನ್ನು ಬಳಸಿ.",
  "Report submitted. Authorities have been notified.":
    "ವರದಿ ಕಳುಹಿಸಲಾಗಿದೆ. ಅಧಿಕಾರಿಗಳಿಗೆ ತಿಳಿಸಲಾಗಿದೆ.",
  "Official warnings near you, updated continuously":
    "ನಿಮ್ಮ ಹತ್ತಿರದ ಅಧಿಕೃತ ಎಚ್ಚರಿಕೆಗಳು, ನಿರಂತರವಾಗಿ ನವೀಕರಿಸಲಾಗುತ್ತದೆ",
  "Nearest shelters and resources on the map": "ನಕ್ಷೆಯಲ್ಲಿ ಹತ್ತಿರದ ಆಶ್ರಯಗಳು ಮತ್ತು ಸಂಪನ್ಮೂಲಗಳು",
  "Fire, police, ambulance, disaster helplines":
    "ಅಗ್ನಿಶಾಮಕ, ಪೊಲೀಸ್, ಆಂಬ್ಯುಲೆನ್ಸ್, ವಿಪತ್ತು ಸಹಾಯವಾಣಿಗಳು",
  "This site is blocked from using your location.":
    "ಈ ಸೈಟ್‌ಗೆ ನಿಮ್ಮ ಸ್ಥಳ ಬಳಸುವುದನ್ನು ತಡೆಯಲಾಗಿದೆ.",
  "Allow location for this site in your browser settings, then try again — or just name your place below.":
    "ನಿಮ್ಮ ಬ್ರೌಸರ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳಲ್ಲಿ ಈ ಸೈಟ್‌ಗೆ ಸ್ಥಳದ ಅನುಮತಿ ನೀಡಿ, ನಂತರ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ — ಅಥವಾ ಕೆಳಗೆ ನಿಮ್ಮ ಸ್ಥಳಕ್ಕೆ ಹೆಸರಿಸಿ.",
  "Your device didn't return a location in time.": "ನಿಮ್ಮ ಸಾಧನ ಸಮಯಕ್ಕೆ ಸ್ಥಳವನ್ನು ನೀಡಲಿಲ್ಲ.",
  "Moving outdoors usually helps, or name your place below.":
    "ಹೊರಗೆ ಹೋಗುವುದು ಸಾಮಾನ್ಯವಾಗಿ ಸಹಾಯ ಮಾಡುತ್ತದೆ, ಅಥವಾ ಕೆಳಗೆ ನಿಮ್ಮ ಸ್ಥಳಕ್ಕೆ ಹೆಸರಿಸಿ.",
  "Your device couldn't determine a location.": "ನಿಮ್ಮ ಸಾಧನಕ್ಕೆ ಸ್ಥಳವನ್ನು ನಿರ್ಧರಿಸಲಾಗಲಿಲ್ಲ.",
  "Common on a desktop with no GPS, and on a phone with Location Services switched off. Name your place below instead.":
    "ಜಿಪಿಎಸ್ ಇಲ್ಲದ ಕಂಪ್ಯೂಟರ್‌ನಲ್ಲಿ ಮತ್ತು ಸ್ಥಳ ಸೇವೆಗಳು ಆಫ್ ಇರುವ ಫೋನ್‌ನಲ್ಲಿ ಇದು ಸಾಮಾನ್ಯ. ಬದಲಿಗೆ ಕೆಳಗೆ ನಿಮ್ಮ ಸ್ಥಳಕ್ಕೆ ಹೆಸರಿಸಿ.",
  "This browser doesn't support location lookup.": "ಈ ಬ್ರೌಸರ್ ಸ್ಥಳ ಹುಡುಕಾಟವನ್ನು ಬೆಂಬಲಿಸುವುದಿಲ್ಲ.",
  "Name your place below instead.": "ಬದಲಿಗೆ ಕೆಳಗೆ ನಿಮ್ಮ ಸ್ಥಳಕ್ಕೆ ಹೆಸರಿಸಿ.",
  "This page is not on a secure (https) connection, so the browser will not share your location.":
    "ಈ ಪುಟ ಸುರಕ್ಷಿತ (https) ಸಂಪರ್ಕದಲ್ಲಿ ಇಲ್ಲ, ಆದ್ದರಿಂದ ಬ್ರೌಸರ್ ನಿಮ್ಮ ಸ್ಥಳವನ್ನು ಹಂಚಿಕೊಳ್ಳುವುದಿಲ್ಲ.",
  "Open the deployed https site, or name your place below.":
    "https ಸೈಟ್ ತೆರೆಯಿರಿ, ಅಥವಾ ಕೆಳಗೆ ನಿಮ್ಮ ಸ್ಥಳಕ್ಕೆ ಹೆಸರಿಸಿ.",

  // Strings the citizen web view has and the app does not.
  "Hospitals": "ಆಸ್ಪತ್ರೆಗಳು",
  "Police stations": "ಪೊಲೀಸ್ ಠಾಣೆಗಳು",
  "Fire stations": "ಅಗ್ನಿಶಾಮಕ ಠಾಣೆಗಳು",
  "Zoom in to see facilities": "ಸೌಲಭ್ಯಗಳನ್ನು ನೋಡಲು ಜೂಮ್ ಮಾಡಿ",
  "None nearby": "ಹತ್ತಿರ ಯಾವುದೂ ಇಲ್ಲ",
  "Showing {shown} of {total}": "{total} ರಲ್ಲಿ {shown} ತೋರಿಸಲಾಗುತ್ತಿದೆ",
  "{n} nearby": "ಹತ್ತಿರ {n}",
  "Could not load facilities": "ಸೌಲಭ್ಯಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗಲಿಲ್ಲ",
};
