// Generated by scripts/sync-shared-lib.js — edit the citizen-app copy, not this one.
import type { Dictionary } from "../translate";

/** Malayalam. MACHINE-TRANSLATED, NOT REVIEWED. Check the SOS and severity lines first. */
export const ml: Dictionary = {
  Home: "ഹോം",
  Report: "റിപ്പോർട്ട്",
  Alerts: "മുന്നറിയിപ്പുകൾ",
  Shelter: "അഭയകേന്ദ്രം",
  Mine: "എന്റേത്",
  Help: "സഹായം",
  Dashboard: "ഡാഷ്ബോർഡ്",
  "Live Alerts": "തത്സമയ മുന്നറിയിപ്പുകൾ",
  "Find Shelter": "അഭയകേന്ദ്രം കണ്ടെത്തുക",
  "My Reports": "എന്റെ റിപ്പോർട്ടുകൾ",
  "Emergency Contacts": "അടിയന്തര ബന്ധപ്പെടേണ്ട നമ്പറുകൾ",
  "Report an Incident": "സംഭവം അറിയിക്കുക",

  "Alerts, shelters and teams nearest to where you are":
    "നിങ്ങൾക്ക് ഏറ്റവും അടുത്തുള്ള മുന്നറിയിപ്പുകൾ, അഭയകേന്ദ്രങ്ങൾ, സംഘങ്ങൾ",
  "Photo, location, severity — filed in under a minute":
    "ചിത്രം, സ്ഥലം, തീവ്രത — ഒരു മിനിറ്റിനുള്ളിൽ രേഖപ്പെടുത്താം",
  "Official warnings within {km} km of you":
    "നിങ്ങളിൽ നിന്ന് {km} കി.മീ. ഉള്ളിലെ ഔദ്യോഗിക മുന്നറിയിപ്പുകൾ",
  "Track the status of what you have reported":
    "നിങ്ങൾ അറിയിച്ചതിന്റെ നില പരിശോധിക്കുക",
  "Tap any number to call directly": "നേരിട്ട് വിളിക്കാൻ ഏതെങ്കിലും നമ്പറിൽ ടാപ്പ് ചെയ്യുക",
  "Shelters, teams and supply points on the map":
    "ഭൂപടത്തിൽ അഭയകേന്ദ്രങ്ങൾ, സംഘങ്ങൾ, വിതരണ കേന്ദ്രങ്ങൾ",
  "Nearest open shelter: {name}, {km} km": "അടുത്തുള്ള തുറന്ന അഭയകേന്ദ്രം: {name}, {km} കി.മീ.",

  "SOS — hold to send": "എസ്ഒഎസ് — അയയ്ക്കാൻ അമർത്തിപ്പിടിക്കുക",
  "Keep holding…": "അമർത്തിപ്പിടിക്കുക…",
  "Sending…": "അയയ്ക്കുന്നു…",
  "Send an SOS": "എസ്ഒഎസ് അയയ്ക്കുക",
  "Press and hold for just over a second to file a critical report at your location":
    "നിങ്ങളുടെ സ്ഥലത്തുനിന്ന് അടിയന്തര റിപ്പോർട്ട് നൽകാൻ ഒരു സെക്കൻഡിൽ അല്പം കൂടുതൽ അമർത്തിപ്പിടിക്കുക",
  "Files a critical report at your location. No description needed.":
    "നിങ്ങളുടെ സ്ഥലത്തുനിന്ന് അടിയന്തര റിപ്പോർട്ട് നൽകുന്നു. വിവരണം ആവശ്യമില്ല.",
  "Set your location below before sending an SOS.":
    "എസ്ഒഎസ് അയയ്ക്കുന്നതിന് മുമ്പ് താഴെ നിങ്ങളുടെ സ്ഥലം നിശ്ചയിക്കുക.",
  "SOS sent": "എസ്ഒഎസ് അയച്ചു",
  "SOS saved offline": "എസ്ഒഎസ് ഓഫ്‌ലൈനിൽ സൂക്ഷിച്ചു",
  "SOS could not be saved": "എസ്ഒഎസ് സൂക്ഷിക്കാനായില്ല",
  "Try again, or call 112.": "വീണ്ടും ശ്രമിക്കുക, അല്ലെങ്കിൽ 112-ൽ വിളിക്കുക.",
  "Authorities have been notified of your location.":
    "അധികൃതരെ നിങ്ങളുടെ സ്ഥലം അറിയിച്ചിട്ടുണ്ട്.",
  "No connection right now. It will send automatically when you are back online. If you can, call 112.":
    "ഇപ്പോൾ കണക്ഷനില്ല. ഓൺലൈനായാൽ ഉടൻ ഇത് സ്വയം അയയ്ക്കപ്പെടും. കഴിയുമെങ്കിൽ 112-ൽ വിളിക്കുക.",

  Location: "സ്ഥലം",
  Severity: "തീവ്രത",
  Description: "വിവരണം",
  "Photo (optional)": "ചിത്രം (നിർബന്ധമല്ല)",
  "Take a photo": "ചിത്രം എടുക്കുക",
  "Choose existing": "നിലവിലുള്ളത് തിരഞ്ഞെടുക്കുക",
  "Submit Report": "റിപ്പോർട്ട് അയയ്ക്കുക",
  "What's happening? Who's affected?": "എന്താണ് സംഭവിക്കുന്നത്? ആരെയാണ് ബാധിച്ചത്?",
  "Location required": "സ്ഥലം ആവശ്യമാണ്",
  "Tag your location before submitting.": "അയയ്ക്കുന്നതിന് മുമ്പ് നിങ്ങളുടെ സ്ഥലം രേഖപ്പെടുത്തുക.",
  "Report submitted": "റിപ്പോർട്ട് അയച്ചു",
  "Authorities have been notified.": "അധികൃതരെ അറിയിച്ചിട്ടുണ്ട്.",
  "Authorities have been notified. Your photo could not be uploaded.":
    "അധികൃതരെ അറിയിച്ചിട്ടുണ്ട്. നിങ്ങളുടെ ചിത്രം അപ്‌ലോഡ് ചെയ്യാനായില്ല.",
  "Could not save your report": "നിങ്ങളുടെ റിപ്പോർട്ട് സൂക്ഷിക്കാനായില്ല",
  "Please try again.": "ദയവായി വീണ്ടും ശ്രമിക്കുക.",
  "Camera permission needed": "ക്യാമറ അനുമതി ആവശ്യമാണ്",
  "Allow camera access to photograph the incident, or choose an existing photo instead.":
    "സംഭവത്തിന്റെ ചിത്രമെടുക്കാൻ ക്യാമറ അനുമതി നൽകുക, അല്ലെങ്കിൽ പകരം നിലവിലുള്ള ഒരു ചിത്രം തിരഞ്ഞെടുക്കുക.",
  "Photo permission needed": "ചിത്ര അനുമതി ആവശ്യമാണ്",
  "Enable photo access to attach an image.": "ചിത്രം ചേർക്കാൻ ചിത്ര അനുമതി ഓണാക്കുക.",

  "Saved offline": "ഓഫ്‌ലൈനിൽ സൂക്ഷിച്ചു",
  "No connection right now. Your report is saved and will be sent automatically when you're back online.":
    "ഇപ്പോൾ കണക്ഷനില്ല. നിങ്ങളുടെ റിപ്പോർട്ട് സൂക്ഷിച്ചിട്ടുണ്ട്, ഓൺലൈനായാൽ ഉടൻ സ്വയം അയയ്ക്കപ്പെടും.",
  "1 report waiting to send": "1 റിപ്പോർട്ട് അയയ്ക്കാൻ കാത്തിരിക്കുന്നു",
  "{count} reports waiting to send": "{count} റിപ്പോർട്ടുകൾ അയയ്ക്കാൻ കാത്തിരിക്കുന്നു",
  "Saved on this device. They'll upload automatically once you're back online.":
    "ഈ ഉപകരണത്തിൽ സൂക്ഷിച്ചിട്ടുണ്ട്. ഓൺലൈനായാൽ ഉടൻ സ്വയം അപ്‌ലോഡ് ചെയ്യപ്പെടും.",
  "Send by SMS instead": "പകരം എസ്എംഎസ് വഴി അയയ്ക്കുക",
  "Opens your messages app. Works without mobile data.":
    "നിങ്ങളുടെ സന്ദേശ ആപ്പ് തുറക്കുന്നു. മൊബൈൽ ഡാറ്റയില്ലാതെ പ്രവർത്തിക്കുന്നു.",
  "Send the oldest waiting report as a text message":
    "കാത്തിരിക്കുന്ന ഏറ്റവും പഴയ റിപ്പോർട്ട് സന്ദേശമായി അയയ്ക്കുക",
  "Could not open messages": "സന്ദേശ ആപ്പ് തുറക്കാനായില്ല",
  "Open your messages app and send this to the Aapda Mitra number:":
    "നിങ്ങളുടെ സന്ദേശ ആപ്പ് തുറന്ന് ഇത് ആപദ മിത്ര നമ്പറിലേക്ക് അയയ്ക്കുക:",

  "Your position": "നിങ്ങളുടെ സ്ഥാനം",
  "Finding your location…": "നിങ്ങളുടെ സ്ഥലം കണ്ടെത്തുന്നു…",
  "Use my location": "എന്റെ സ്ഥലം ഉപയോഗിക്കുക",
  "Update location": "സ്ഥലം പുതുക്കുക",
  "Name my place": "എന്റെ സ്ഥലത്തിന് പേര് നൽകുക",
  "Where are you?": "നിങ്ങൾ എവിടെയാണ്?",
  State: "സംസ്ഥാനം",
  District: "ജില്ല",
  "Town or city": "പട്ടണം അല്ലെങ്കിൽ നഗരം",
  "No town is listed here": "ഇവിടെ ഒരു പട്ടണവും പട്ടികയിലില്ല",
  "Search {towns} towns, {districts} districts": "{towns} പട്ടണങ്ങൾ, {districts} ജില്ലകളിൽ തിരയുക",
  "Filter {n} towns": "{n} പട്ടണങ്ങൾ അരിച്ചെടുക്കുക",
  approximate: "ഏകദേശം",
  "approximate, set by hand": "ഏകദേശം, കൈകൊണ്ട് നൽകിയത്",
  "Location access is turned off for this app. Allow it in Settings, or name your place below.":
    "ഈ ആപ്പിന് സ്ഥല അനുമതി ഓഫാണ്. ക്രമീകരണങ്ങളിൽ അത് നൽകുക, അല്ലെങ്കിൽ താഴെ നിങ്ങളുടെ സ്ഥലത്തിന് പേര് നൽകുക.",
  "Location Services is switched off on this device. Turn it on, or name your place below.":
    "ഈ ഉപകരണത്തിൽ ലൊക്കേഷൻ സേവനങ്ങൾ ഓഫാണ്. അത് ഓണാക്കുക, അല്ലെങ്കിൽ താഴെ നിങ്ങളുടെ സ്ഥലത്തിന് പേര് നൽകുക.",
  "Your device didn't return a location in time. Moving outdoors often helps.":
    "നിങ്ങളുടെ ഉപകരണം സമയത്ത് സ്ഥലം നൽകിയില്ല. പുറത്തേക്ക് നീങ്ങുന്നത് പലപ്പോഴും സഹായിക്കും.",
  "Location lookup failed. You can name your place instead.":
    "സ്ഥലം കണ്ടെത്താനായില്ല. പകരം നിങ്ങളുടെ സ്ഥലത്തിന് പേര് നൽകാം.",

  "Active alerts within {km} km": "{km} കി.മീ. ഉള്ളിലെ സജീവ മുന്നറിയിപ്പുകൾ",
  "Most severe: {type}{agency} · {km} away": "ഏറ്റവും തീവ്രം: {type}{agency} · {km} അകലെ",
  "No official warnings currently cover your area.":
    "നിലവിൽ നിങ്ങളുടെ പ്രദേശത്തിന് ഔദ്യോഗിക മുന്നറിയിപ്പുകളൊന്നുമില്ല.",
  "Nearest available shelter": "അടുത്തുള്ള ലഭ്യമായ അഭയകേന്ദ്രം",
  "No shelter is currently marked available in the registry.":
    "നിലവിൽ രജിസ്റ്ററിൽ ഒരു അഭയകേന്ദ്രവും ലഭ്യമെന്ന് രേഖപ്പെടുത്തിയിട്ടില്ല.",
  "Nearest available rescue team": "അടുത്തുള്ള ലഭ്യമായ രക്ഷാസംഘം",
  "No rescue team is currently marked available.":
    "നിലവിൽ ഒരു രക്ഷാസംഘവും ലഭ്യമെന്ന് രേഖപ്പെടുത്തിയിട്ടില്ല.",
  "Your open reports": "നിങ്ങളുടെ തീർപ്പാകാത്ത റിപ്പോർട്ടുകൾ",
  "Still being worked. Track them under My Reports.":
    "ഇപ്പോഴും നടപടി നടക്കുന്നു. എന്റെ റിപ്പോർട്ടുകളിൽ അവ കാണുക.",
  "Nothing outstanding from you right now.": "ഇപ്പോൾ നിങ്ങളുടേതായി ഒന്നും ബാക്കിയില്ല.",
  "None listed": "ഒന്നുമില്ല",
  "capacity {n}": "ശേഷി {n}",
  "No active alerts nearby.": "അടുത്ത് സജീവ മുന്നറിയിപ്പുകളൊന്നുമില്ല.",
  "You haven't submitted any reports yet.": "നിങ്ങൾ ഇതുവരെ ഒരു റിപ്പോർട്ടും അയച്ചിട്ടില്ല.",

  low: "കുറവ്",
  medium: "ഇടത്തരം",
  high: "കൂടുതൽ",
  critical: "അതീവ ഗുരുതരം",
  advisory: "അറിയിപ്പ്",
  watch: "ജാഗ്രത",
  warning: "മുന്നറിയിപ്പ്",
  severe: "ഗുരുതരം",
  open: "തുറന്നിരിക്കുന്നു",
  assigned: "ഏൽപ്പിച്ചു",
  resolved: "പരിഹരിച്ചു",
  available: "ലഭ്യം",
  full: "നിറഞ്ഞു",
  dispatched: "അയച്ചു",
  shelter: "അഭയകേന്ദ്രം",
  "rescue team": "രക്ഷാസംഘം",
  "supply stock": "വിതരണ ശേഖരം",
  Open: "തുറന്നിരിക്കുന്നു",
  Full: "നിറഞ്ഞു",
  "Out on a call": "ജോലിക്ക് പോയിരിക്കുന്നു",

  "National Emergency Number": "ദേശീയ അടിയന്തര നമ്പർ",
  Police: "പോലീസ്",
  Fire: "അഗ്നിരക്ഷാ സേന",
  Ambulance: "ആംബുലൻസ്",
  "NDMA Disaster Management Helpline": "എൻഡിഎംഎ ദുരന്ത നിവാരണ ഹെൽപ്‌ലൈൻ",
  "Women's Helpline": "വനിതാ ഹെൽപ്‌ലൈൻ",
  "Call {name} on {number}": "{name} എന്നതിലേക്ക് {number}-ൽ വിളിക്കുക",

  Close: "അടയ്ക്കുക",
  Change: "മാറ്റുക",
  "Change language": "ഭാഷ മാറ്റുക",
  "Choose your language": "നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക",

  // Strings the citizen web view has and the app does not.
  "Sign out": "സൈൻ ഔട്ട്",
  "Try again": "വീണ്ടും ശ്രമിക്കുക",
  "Submitting…": "അയയ്ക്കുന്നു…",
  "Hide place list": "സ്ഥലങ്ങളുടെ പട്ടിക മറയ്ക്കുക",
  "Attached photo preview": "ചേർത്ത ചിത്രത്തിന്റെ പ്രിവ്യൂ",
  "Search for your city or district": "നിങ്ങളുടെ നഗരമോ ജില്ലയോ തിരയുക",
  "Search {cities} cities, {districts} districts…":
    "{cities} നഗരങ്ങൾ, {districts} ജില്ലകളിൽ തിരയുക…",
  "Filter {n} towns…": "{n} പട്ടണങ്ങൾ അരിച്ചെടുക്കുക…",
  "Location not available yet — allow location access and try again.":
    "സ്ഥലം ഇതുവരെ ലഭ്യമല്ല — സ്ഥല അനുമതി നൽകി വീണ്ടും ശ്രമിക്കുക.",
  "Set your location first — use the readout above.":
    "ആദ്യം നിങ്ങളുടെ സ്ഥലം നിശ്ചയിക്കുക — മുകളിലെ വിവരം ഉപയോഗിക്കുക.",
  "Report submitted. Authorities have been notified.":
    "റിപ്പോർട്ട് അയച്ചു. അധികൃതരെ അറിയിച്ചിട്ടുണ്ട്.",
  "Official warnings near you, updated continuously":
    "നിങ്ങളുടെ അടുത്തുള്ള ഔദ്യോഗിക മുന്നറിയിപ്പുകൾ, തുടർച്ചയായി പുതുക്കുന്നു",
  "Nearest shelters and resources on the map": "ഭൂപടത്തിൽ അടുത്തുള്ള അഭയകേന്ദ്രങ്ങളും വിഭവങ്ങളും",
  "Fire, police, ambulance, disaster helplines":
    "അഗ്നിരക്ഷാ സേന, പോലീസ്, ആംബുലൻസ്, ദുരന്ത ഹെൽപ്‌ലൈനുകൾ",
  "This site is blocked from using your location.":
    "ഈ സൈറ്റിന് നിങ്ങളുടെ സ്ഥലം ഉപയോഗിക്കുന്നത് തടഞ്ഞിരിക്കുന്നു.",
  "Allow location for this site in your browser settings, then try again — or just name your place below.":
    "നിങ്ങളുടെ ബ്രൗസർ ക്രമീകരണങ്ങളിൽ ഈ സൈറ്റിന് സ്ഥല അനുമതി നൽകി വീണ്ടും ശ്രമിക്കുക — അല്ലെങ്കിൽ താഴെ നിങ്ങളുടെ സ്ഥലത്തിന് പേര് നൽകുക.",
  "Your device didn't return a location in time.": "നിങ്ങളുടെ ഉപകരണം സമയത്ത് സ്ഥലം നൽകിയില്ല.",
  "Moving outdoors usually helps, or name your place below.":
    "പുറത്തേക്ക് നീങ്ങുന്നത് സാധാരണയായി സഹായിക്കും, അല്ലെങ്കിൽ താഴെ നിങ്ങളുടെ സ്ഥലത്തിന് പേര് നൽകുക.",
  "Your device couldn't determine a location.":
    "നിങ്ങളുടെ ഉപകരണത്തിന് സ്ഥലം നിർണ്ണയിക്കാനായില്ല.",
  "Common on a desktop with no GPS, and on a phone with Location Services switched off. Name your place below instead.":
    "ജിപിഎസ് ഇല്ലാത്ത കമ്പ്യൂട്ടറിലും ലൊക്കേഷൻ സേവനങ്ങൾ ഓഫായ ഫോണിലും ഇത് സാധാരണമാണ്. പകരം താഴെ നിങ്ങളുടെ സ്ഥലത്തിന് പേര് നൽകുക.",
  "This browser doesn't support location lookup.":
    "ഈ ബ്രൗസർ സ്ഥലം കണ്ടെത്തലിനെ പിന്തുണയ്ക്കുന്നില്ല.",
  "Name your place below instead.": "പകരം താഴെ നിങ്ങളുടെ സ്ഥലത്തിന് പേര് നൽകുക.",
  "This page is not on a secure (https) connection, so the browser will not share your location.":
    "ഈ പേജ് സുരക്ഷിതമായ (https) കണക്ഷനിലല്ല, അതിനാൽ ബ്രൗസർ നിങ്ങളുടെ സ്ഥലം പങ്കിടില്ല.",
  "Open the deployed https site, or name your place below.":
    "https സൈറ്റ് തുറക്കുക, അല്ലെങ്കിൽ താഴെ നിങ്ങളുടെ സ്ഥലത്തിന് പേര് നൽകുക.",

  // Strings the citizen web view has and the app does not.
  "Hospitals": "ആശുപത്രികൾ",
  "Police stations": "പോലീസ് സ്റ്റേഷനുകൾ",
  "Fire stations": "അഗ്നിശമന നിലയങ്ങൾ",
  "Zoom in to see facilities": "സൗകര്യങ്ങൾ കാണാൻ സൂം ചെയ്യുക",
  "None nearby": "അടുത്ത് ഒന്നുമില്ല",
  "Showing {shown} of {total}": "{total}-ൽ {shown} കാണിക്കുന്നു",
  "{n} nearby": "അടുത്ത് {n}",
  "Could not load facilities": "സൗകര്യങ്ങൾ ലോഡ് ചെയ്യാനായില്ല",
};
