// Generated by scripts/sync-shared-lib.js — edit the citizen-app copy, not this one.
import type { Dictionary } from "../translate";

/** Odia. MACHINE-TRANSLATED, NOT REVIEWED. Check the SOS and severity lines first. */
export const or: Dictionary = {
  Home: "ମୁଖ୍ୟପୃଷ୍ଠା",
  Report: "ରିପୋର୍ଟ",
  Alerts: "ସତର୍କତା",
  Shelter: "ଆଶ୍ରୟ",
  Mine: "ମୋର",
  Help: "ସାହାଯ୍ୟ",
  Dashboard: "ଡ୍ୟାସବୋର୍ଡ",
  "Live Alerts": "ସିଧାସଳଖ ସତର୍କତା",
  "Find Shelter": "ଆଶ୍ରୟ ଖୋଜନ୍ତୁ",
  "My Reports": "ମୋର ରିପୋର୍ଟ",
  "Emergency Contacts": "ଜରୁରୀକାଳୀନ ଯୋଗାଯୋଗ",
  "Report an Incident": "ଘଟଣା ବିଷୟରେ ଜଣାନ୍ତୁ",

  "Alerts, shelters and teams nearest to where you are":
    "ଆପଣଙ୍କ ନିକଟତମ ସତର୍କତା, ଆଶ୍ରୟସ୍ଥଳୀ ଏବଂ ଦଳ",
  "Photo, location, severity — filed in under a minute":
    "ଫଟୋ, ସ୍ଥାନ, ଗମ୍ଭୀରତା — ଏକ ମିନିଟ୍ ଭିତରେ ଦାଖଲ",
  "Official warnings within {km} km of you": "ଆପଣଙ୍କଠାରୁ {km} କି.ମି. ଭିତରେ ସରକାରୀ ସତର୍କତା",
  "Track the status of what you have reported": "ଆପଣ ଯାହା ଜଣାଇଛନ୍ତି ତାହାର ସ୍ଥିତି ଦେଖନ୍ତୁ",
  "Tap any number to call directly": "ସିଧାସଳଖ କଲ୍ କରିବାକୁ ଯେକୌଣସି ନମ୍ବରରେ ଟାପ୍ କରନ୍ତୁ",
  "Shelters, teams and supply points on the map":
    "ମାନଚିତ୍ରରେ ଆଶ୍ରୟସ୍ଥଳୀ, ଦଳ ଏବଂ ଯୋଗାଣ କେନ୍ଦ୍ର",
  "Nearest open shelter: {name}, {km} km": "ନିକଟତମ ଖୋଲା ଆଶ୍ରୟସ୍ଥଳୀ: {name}, {km} କି.ମି.",

  "SOS — hold to send": "ଏସଓଏସ୍ — ପଠାଇବାକୁ ଚାପି ଧରନ୍ତୁ",
  "Keep holding…": "ଚାପି ଧରନ୍ତୁ…",
  "Sending…": "ପଠାଯାଉଛି…",
  "Send an SOS": "ଏସଓଏସ୍ ପଠାନ୍ତୁ",
  "Press and hold for just over a second to file a critical report at your location":
    "ଆପଣଙ୍କ ସ୍ଥାନରୁ ଗମ୍ଭୀର ରିପୋର୍ଟ ଦାଖଲ କରିବାକୁ ଏକ ସେକେଣ୍ଡରୁ ଟିକେ ଅଧିକ ଚାପି ଧରନ୍ତୁ",
  "Files a critical report at your location. No description needed.":
    "ଆପଣଙ୍କ ସ୍ଥାନରୁ ଗମ୍ଭୀର ରିପୋର୍ଟ ଦାଖଲ କରେ। ବିବରଣୀ ଆବଶ୍ୟକ ନାହିଁ।",
  "Set your location below before sending an SOS.":
    "ଏସଓଏସ୍ ପଠାଇବା ପୂର୍ବରୁ ତଳେ ଆପଣଙ୍କ ସ୍ଥାନ ନିର୍ଣ୍ଣୟ କରନ୍ତୁ।",
  "SOS sent": "ଏସଓଏସ୍ ପଠାଯାଇଛି",
  "SOS saved offline": "ଏସଓଏସ୍ ଅଫଲାଇନରେ ସଞ୍ଚିତ",
  "SOS could not be saved": "ଏସଓଏସ୍ ସଞ୍ଚୟ କରାଯାଇପାରିଲା ନାହିଁ",
  "Try again, or call 112.": "ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ, କିମ୍ବା ୧୧୨କୁ କଲ୍ କରନ୍ତୁ।",
  "Authorities have been notified of your location.":
    "କର୍ତ୍ତୃପକ୍ଷଙ୍କୁ ଆପଣଙ୍କ ସ୍ଥାନ ବିଷୟରେ ଜଣାଇ ଦିଆଯାଇଛି।",
  "No connection right now. It will send automatically when you are back online. If you can, call 112.":
    "ଏବେ କୌଣସି ସଂଯୋଗ ନାହିଁ। ଆପଣ ଅନଲାଇନକୁ ଫେରିଲେ ଏହା ନିଜେ ପଠାଯିବ। ସମ୍ଭବ ହେଲେ ୧୧୨କୁ କଲ୍ କରନ୍ତୁ।",

  Location: "ସ୍ଥାନ",
  Severity: "ଗମ୍ଭୀରତା",
  Description: "ବିବରଣୀ",
  "Photo (optional)": "ଫଟୋ (ଐଚ୍ଛିକ)",
  "Take a photo": "ଫଟୋ ନିଅନ୍ତୁ",
  "Choose existing": "ପୂର୍ବରୁ ଥିବାଟି ବାଛନ୍ତୁ",
  "Submit Report": "ରିପୋର୍ଟ ପଠାନ୍ତୁ",
  "What's happening? Who's affected?": "କଣ ଘଟୁଛି? କିଏ ପ୍ରଭାବିତ?",
  "Location required": "ସ୍ଥାନ ଆବଶ୍ୟକ",
  "Tag your location before submitting.": "ପଠାଇବା ପୂର୍ବରୁ ଆପଣଙ୍କ ସ୍ଥାନ ଦିଅନ୍ତୁ।",
  "Report submitted": "ରିପୋର୍ଟ ପଠାଯାଇଛି",
  "Authorities have been notified.": "କର୍ତ୍ତୃପକ୍ଷଙ୍କୁ ଜଣାଇ ଦିଆଯାଇଛି।",
  "Authorities have been notified. Your photo could not be uploaded.":
    "କର୍ତ୍ତୃପକ୍ଷଙ୍କୁ ଜଣାଇ ଦିଆଯାଇଛି। ଆପଣଙ୍କ ଫଟୋ ଅପଲୋଡ୍ ହୋଇପାରିଲା ନାହିଁ।",
  "Could not save your report": "ଆପଣଙ୍କ ରିପୋର୍ଟ ସଞ୍ଚୟ କରାଯାଇପାରିଲା ନାହିଁ",
  "Please try again.": "ଦୟାକରି ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ।",
  "Camera permission needed": "କ୍ୟାମେରା ଅନୁମତି ଆବଶ୍ୟକ",
  "Allow camera access to photograph the incident, or choose an existing photo instead.":
    "ଘଟଣାର ଫଟୋ ନେବାକୁ କ୍ୟାମେରା ଅନୁମତି ଦିଅନ୍ତୁ, କିମ୍ବା ପରିବର୍ତ୍ତେ ପୂର୍ବରୁ ଥିବା ଫଟୋ ବାଛନ୍ତୁ।",
  "Photo permission needed": "ଫଟୋ ଅନୁମତି ଆବଶ୍ୟକ",
  "Enable photo access to attach an image.": "ଛବି ଯୋଡ଼ିବାକୁ ଫଟୋ ଅନୁମତି ଚାଲୁ କରନ୍ତୁ।",

  "Saved offline": "ଅଫଲାଇନରେ ସଞ୍ଚିତ",
  "No connection right now. Your report is saved and will be sent automatically when you're back online.":
    "ଏବେ କୌଣସି ସଂଯୋଗ ନାହିଁ। ଆପଣଙ୍କ ରିପୋର୍ଟ ସଞ୍ଚିତ ହୋଇଛି ଏବଂ ଅନଲାଇନକୁ ଫେରିଲେ ନିଜେ ପଠାଯିବ।",
  "1 report waiting to send": "୧ଟି ରିପୋର୍ଟ ପଠାଇବା ବାକି",
  "{count} reports waiting to send": "{count}ଟି ରିପୋର୍ଟ ପଠାଇବା ବାକି",
  "Saved on this device. They'll upload automatically once you're back online.":
    "ଏହି ଉପକରଣରେ ସଞ୍ଚିତ। ଅନଲାଇନକୁ ଫେରିଲେ ନିଜେ ଅପଲୋଡ୍ ହୋଇଯିବ।",
  "Send by SMS instead": "ପରିବର୍ତ୍ତେ ଏସଏମଏସ୍ ଦ୍ୱାରା ପଠାନ୍ତୁ",
  "Opens your messages app. Works without mobile data.":
    "ଆପଣଙ୍କ ମେସେଜ୍ ଆପ୍ ଖୋଲେ। ମୋବାଇଲ୍ ଡାଟା ବିନା କାମ କରେ।",
  "Send the oldest waiting report as a text message":
    "ସବୁଠାରୁ ପୁରୁଣା ବାକି ରିପୋର୍ଟକୁ ମେସେଜ୍ ଭାବରେ ପଠାନ୍ତୁ",
  "Could not open messages": "ମେସେଜ୍ ଆପ୍ ଖୋଲିପାରିଲା ନାହିଁ",
  "Open your messages app and send this to the Aapda Mitra number:":
    "ଆପଣଙ୍କ ମେସେଜ୍ ଆପ୍ ଖୋଲି ଏହା ଆପଦା ମିତ୍ର ନମ୍ବରକୁ ପଠାନ୍ତୁ:",

  "Your position": "ଆପଣଙ୍କ ଅବସ୍ଥାନ",
  "Finding your location…": "ଆପଣଙ୍କ ସ୍ଥାନ ଖୋଜାଯାଉଛି…",
  "Use my location": "ମୋ ସ୍ଥାନ ବ୍ୟବହାର କରନ୍ତୁ",
  "Update location": "ସ୍ଥାନ ଅଦ୍ୟତନ କରନ୍ତୁ",
  "Name my place": "ମୋ ଜାଗାର ନାମ ଦିଅନ୍ତୁ",
  "Where are you?": "ଆପଣ କେଉଁଠି ଅଛନ୍ତି?",
  State: "ରାଜ୍ୟ",
  District: "ଜିଲ୍ଲା",
  "Town or city": "ସହର କିମ୍ବା ନଗର",
  "No town is listed here": "ଏଠାରେ କୌଣସି ସହର ତାଲିକାଭୁକ୍ତ ନାହିଁ",
  "Search {towns} towns, {districts} districts": "{towns} ସହର, {districts} ଜିଲ୍ଲାରେ ଖୋଜନ୍ତୁ",
  "Filter {n} towns": "{n} ସହର ଛାଣନ୍ତୁ",
  approximate: "ଆନୁମାନିକ",
  "approximate, set by hand": "ଆନୁମାନିକ, ହାତରେ ଦିଆଯାଇଛି",
  "Location access is turned off for this app. Allow it in Settings, or name your place below.":
    "ଏହି ଆପ୍ ପାଇଁ ସ୍ଥାନ ଅନୁମତି ବନ୍ଦ ଅଛି। ସେଟିଂସରେ ଏହା ଦିଅନ୍ତୁ, କିମ୍ବା ତଳେ ଆପଣଙ୍କ ଜାଗାର ନାମ ଦିଅନ୍ତୁ।",
  "Location Services is switched off on this device. Turn it on, or name your place below.":
    "ଏହି ଉପକରଣରେ ଲୋକେସନ୍ ସେବା ବନ୍ଦ ଅଛି। ଏହା ଚାଲୁ କରନ୍ତୁ, କିମ୍ବା ତଳେ ଆପଣଙ୍କ ଜାଗାର ନାମ ଦିଅନ୍ତୁ।",
  "Your device didn't return a location in time. Moving outdoors often helps.":
    "ଆପଣଙ୍କ ଉପକରଣ ସମୟରେ ସ୍ଥାନ ଦେଲା ନାହିଁ। ଖୋଲା ଜାଗାକୁ ଗଲେ ପ୍ରାୟତଃ ସାହାଯ୍ୟ ମିଳେ।",
  "Location lookup failed. You can name your place instead.":
    "ସ୍ଥାନ ଖୋଜିବା ବିଫଳ ହେଲା। ପରିବର୍ତ୍ତେ ଆପଣ ନିଜ ଜାଗାର ନାମ ଦେଇପାରିବେ।",

  "Active alerts within {km} km": "{km} କି.ମି. ଭିତରେ ସକ୍ରିୟ ସତର୍କତା",
  "Most severe: {type}{agency} · {km} away": "ସବୁଠାରୁ ଗମ୍ଭୀର: {type}{agency} · {km} ଦୂରରେ",
  "No official warnings currently cover your area.":
    "ବର୍ତ୍ତମାନ ଆପଣଙ୍କ ଅଞ୍ଚଳ ପାଇଁ କୌଣସି ସରକାରୀ ସତର୍କତା ନାହିଁ।",
  "Nearest available shelter": "ନିକଟତମ ଉପଲବ୍ଧ ଆଶ୍ରୟସ୍ଥଳୀ",
  "No shelter is currently marked available in the registry.":
    "ବର୍ତ୍ତମାନ ପଞ୍ଜିକାରେ କୌଣସି ଆଶ୍ରୟସ୍ଥଳୀ ଉପଲବ୍ଧ ବୋଲି ଦର୍ଶାଯାଇ ନାହିଁ।",
  "Nearest available rescue team": "ନିକଟତମ ଉପଲବ୍ଧ ଉଦ୍ଧାର ଦଳ",
  "No rescue team is currently marked available.":
    "ବର୍ତ୍ତମାନ କୌଣସି ଉଦ୍ଧାର ଦଳ ଉପଲବ୍ଧ ବୋଲି ଦର୍ଶାଯାଇ ନାହିଁ।",
  "Your open reports": "ଆପଣଙ୍କ ବାକି ରିପୋର୍ଟ",
  "Still being worked. Track them under My Reports.":
    "ଏବେ ବି କାମ ଚାଲିଛି। ମୋର ରିପୋର୍ଟରେ ସେଗୁଡ଼ିକ ଦେଖନ୍ତୁ।",
  "Nothing outstanding from you right now.": "ବର୍ତ୍ତମାନ ଆପଣଙ୍କର କିଛି ବାକି ନାହିଁ।",
  "None listed": "କିଛି ନାହିଁ",
  "capacity {n}": "ଧାରଣ କ୍ଷମତା {n}",
  "No active alerts nearby.": "ଆଖପାଖରେ କୌଣସି ସକ୍ରିୟ ସତର୍କତା ନାହିଁ।",
  "You haven't submitted any reports yet.": "ଆପଣ ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ରିପୋର୍ଟ ପଠାଇ ନାହାନ୍ତି।",

  low: "କମ୍",
  medium: "ମଧ୍ୟମ",
  high: "ଅଧିକ",
  critical: "ଗମ୍ଭୀର",
  advisory: "ସୂଚନା",
  watch: "ନଜରଦାରୀ",
  warning: "ସତର୍କତା",
  severe: "ଅତି ଗମ୍ଭୀର",
  open: "ଖୋଲା",
  assigned: "ନ୍ୟସ୍ତ",
  resolved: "ସମାଧାନ ହୋଇଛି",
  available: "ଉପଲବ୍ଧ",
  full: "ପୂର୍ଣ୍ଣ",
  dispatched: "ପଠାଯାଇଛି",
  shelter: "ଆଶ୍ରୟସ୍ଥଳୀ",
  "rescue team": "ଉଦ୍ଧାର ଦଳ",
  "supply stock": "ଯୋଗାଣ ଭଣ୍ଡାର",
  Open: "ଖୋଲା",
  Full: "ପୂର୍ଣ୍ଣ",
  "Out on a call": "କାମରେ ଯାଇଛି",

  "National Emergency Number": "ଜାତୀୟ ଜରୁରୀକାଳୀନ ନମ୍ବର",
  Police: "ପୋଲିସ",
  Fire: "ଅଗ୍ନିଶମ",
  Ambulance: "ଆମ୍ବୁଲାନ୍ସ",
  "NDMA Disaster Management Helpline": "ଏନଡିଏମଏ ବିପର୍ଯ୍ୟୟ ପରିଚାଳନା ହେଲ୍ପଲାଇନ",
  "Women's Helpline": "ମହିଳା ହେଲ୍ପଲାଇନ",
  "Call {name} on {number}": "{name}ଙ୍କୁ {number}ରେ କଲ୍ କରନ୍ତୁ",

  Close: "ବନ୍ଦ କରନ୍ତୁ",
  Change: "ବଦଳାନ୍ତୁ",
  "Change language": "ଭାଷା ବଦଳାନ୍ତୁ",
  "Choose your language": "ଆପଣଙ୍କ ଭାଷା ବାଛନ୍ତୁ",
};
