// Generated by scripts/sync-shared-lib.js — edit the citizen-app copy, not this one.
import type { Dictionary } from "../translate";

/**
 * Urdu.
 *
 * MACHINE-TRANSLATED, NOT REVIEWED BY A NATIVE SPEAKER. Check the SOS strings,
 * the offline and SMS strings, and the severity words first.
 *
 * Urdu is written right to left. The text engine handles the direction of the
 * words themselves, so sentences read correctly, but the app's layout stays
 * left to right — labels, icons and the back arrow do not mirror. Doing that
 * properly needs I18nManager.forceRTL and an app restart, and it would mirror
 * the layout for Kashmiri and Sindhi too. Left as a known gap rather than a
 * half-applied one; the same note belongs on ks.ts and sd.ts.
 */
export const ur: Dictionary = {
  Home: "ہوم",
  Report: "اطلاع",
  Alerts: "انتباہات",
  Shelter: "پناہ",
  Mine: "میری",
  Help: "مدد",
  Dashboard: "ڈیش بورڈ",
  "Live Alerts": "براہ راست انتباہات",
  "Find Shelter": "پناہ گاہ تلاش کریں",
  "My Reports": "میری اطلاعات",
  "Emergency Contacts": "ہنگامی رابطے",
  "Report an Incident": "واقعے کی اطلاع دیں",

  "Alerts, shelters and teams nearest to where you are":
    "آپ کے قریب ترین انتباہات، پناہ گاہیں اور ٹیمیں",
  "Photo, location, severity — filed in under a minute":
    "تصویر، مقام، شدت — ایک منٹ سے کم میں درج",
  "Official warnings within {km} km of you": "آپ سے {km} کلومیٹر کے اندر سرکاری انتباہات",
  "Track the status of what you have reported": "آپ نے جو اطلاع دی ہے اس کی حالت دیکھیں",
  "Tap any number to call directly": "براہ راست کال کرنے کے لیے کسی بھی نمبر پر ٹیپ کریں",
  "Shelters, teams and supply points on the map": "نقشے پر پناہ گاہیں، ٹیمیں اور رسد مراکز",
  "Nearest open shelter: {name}, {km} km": "قریب ترین کھلی پناہ گاہ: {name}، {km} کلومیٹر",

  "SOS — hold to send": "ایس او ایس — بھیجنے کے لیے دبائے رکھیں",
  "Keep holding…": "دبائے رکھیں…",
  "Sending…": "بھیجا جا رہا ہے…",
  "Send an SOS": "ایس او ایس بھیجیں",
  "Press and hold for just over a second to file a critical report at your location":
    "اپنے مقام سے نازک اطلاع درج کرنے کے لیے ایک سیکنڈ سے کچھ زیادہ دبائے رکھیں",
  "Files a critical report at your location. No description needed.":
    "آپ کے مقام سے نازک اطلاع درج کرتا ہے۔ تفصیل کی ضرورت نہیں۔",
  "Set your location below before sending an SOS.":
    "ایس او ایس بھیجنے سے پہلے نیچے اپنا مقام متعین کریں۔",
  "SOS sent": "ایس او ایس بھیج دیا گیا",
  "SOS saved offline": "ایس او ایس آف لائن محفوظ ہو گیا",
  "SOS could not be saved": "ایس او ایس محفوظ نہ ہو سکا",
  "Try again, or call 112.": "دوبارہ کوشش کریں، یا 112 پر کال کریں۔",
  "Authorities have been notified of your location.":
    "حکام کو آپ کے مقام سے آگاہ کر دیا گیا ہے۔",
  "No connection right now. It will send automatically when you are back online. If you can, call 112.":
    "اس وقت کوئی کنکشن نہیں۔ آن لائن آتے ہی یہ خود بخود بھیج دی جائے گی۔ ہو سکے تو 112 پر کال کریں۔",

  Location: "مقام",
  Severity: "شدت",
  Description: "تفصیل",
  "Photo (optional)": "تصویر (اختیاری)",
  "Take a photo": "تصویر لیں",
  "Choose existing": "موجودہ منتخب کریں",
  "Submit Report": "اطلاع بھیجیں",
  "What's happening? Who's affected?": "کیا ہو رہا ہے؟ کون متاثر ہے؟",
  "Location required": "مقام درکار ہے",
  "Tag your location before submitting.": "بھیجنے سے پہلے اپنا مقام درج کریں۔",
  "Report submitted": "اطلاع بھیج دی گئی",
  "Authorities have been notified.": "حکام کو آگاہ کر دیا گیا ہے۔",
  "Authorities have been notified. Your photo could not be uploaded.":
    "حکام کو آگاہ کر دیا گیا ہے۔ آپ کی تصویر اپ لوڈ نہ ہو سکی۔",
  "Could not save your report": "آپ کی اطلاع محفوظ نہ ہو سکی",
  "Please try again.": "براہ کرم دوبارہ کوشش کریں۔",
  "Camera permission needed": "کیمرے کی اجازت درکار",
  "Allow camera access to photograph the incident, or choose an existing photo instead.":
    "واقعے کی تصویر لینے کے لیے کیمرے کی اجازت دیں، یا اس کے بجائے کوئی موجودہ تصویر منتخب کریں۔",
  "Photo permission needed": "تصویر کی اجازت درکار",
  "Enable photo access to attach an image.": "تصویر منسلک کرنے کے لیے تصاویر کی اجازت آن کریں۔",

  "Saved offline": "آف لائن محفوظ",
  "No connection right now. Your report is saved and will be sent automatically when you're back online.":
    "اس وقت کوئی کنکشن نہیں۔ آپ کی اطلاع محفوظ ہو گئی ہے اور آن لائن آتے ہی خود بخود بھیج دی جائے گی۔",
  "1 report waiting to send": "1 اطلاع بھیجنے کے انتظار میں",
  "{count} reports waiting to send": "{count} اطلاعات بھیجنے کے انتظار میں",
  "Saved on this device. They'll upload automatically once you're back online.":
    "اس آلے پر محفوظ ہیں۔ آن لائن آتے ہی خود بخود اپ لوڈ ہو جائیں گی۔",
  "Send by SMS instead": "اس کے بجائے ایس ایم ایس سے بھیجیں",
  "Opens your messages app. Works without mobile data.":
    "آپ کی پیغامات ایپ کھولتا ہے۔ موبائل ڈیٹا کے بغیر کام کرتا ہے۔",
  "Send the oldest waiting report as a text message":
    "سب سے پرانی زیر التوا اطلاع پیغام کے طور پر بھیجیں",
  "Could not open messages": "پیغامات ایپ نہ کھل سکی",
  "Open your messages app and send this to the Aapda Mitra number:":
    "اپنی پیغامات ایپ کھولیں اور یہ آپدا مترا نمبر پر بھیجیں:",

  "Your position": "آپ کا مقام",
  "Finding your location…": "آپ کا مقام تلاش کیا جا رہا ہے…",
  "Use my location": "میرا مقام استعمال کریں",
  "Update location": "مقام تازہ کریں",
  "Name my place": "اپنی جگہ کا نام دیں",
  "Where are you?": "آپ کہاں ہیں؟",
  State: "ریاست",
  District: "ضلع",
  "Town or city": "قصبہ یا شہر",
  "No town is listed here": "یہاں کوئی قصبہ درج نہیں",
  "Search {towns} towns, {districts} districts": "{towns} قصبے، {districts} اضلاع میں تلاش کریں",
  "Filter {n} towns": "{n} قصبے چھانٹیں",
  approximate: "تخمینی",
  "approximate, set by hand": "تخمینی، ہاتھ سے درج",
  "Location access is turned off for this app. Allow it in Settings, or name your place below.":
    "اس ایپ کے لیے مقام کی اجازت بند ہے۔ ترتیبات میں اسے دیں، یا نیچے اپنی جگہ کا نام دیں۔",
  "Location Services is switched off on this device. Turn it on, or name your place below.":
    "اس آلے پر مقام کی خدمات بند ہیں۔ انہیں آن کریں، یا نیچے اپنی جگہ کا نام دیں۔",
  "Your device didn't return a location in time. Moving outdoors often helps.":
    "آپ کے آلے نے وقت پر مقام نہیں بتایا۔ کھلی جگہ پر جانے سے اکثر مدد ملتی ہے۔",
  "Location lookup failed. You can name your place instead.":
    "مقام معلوم نہ ہو سکا۔ اس کے بجائے آپ اپنی جگہ کا نام دے سکتے ہیں۔",

  "Active alerts within {km} km": "{km} کلومیٹر کے اندر فعال انتباہات",
  "Most severe: {type}{agency} · {km} away": "سب سے شدید: {type}{agency} · {km} دور",
  "No official warnings currently cover your area.":
    "اس وقت آپ کے علاقے کے لیے کوئی سرکاری انتباہ نہیں۔",
  "Nearest available shelter": "قریب ترین دستیاب پناہ گاہ",
  "No shelter is currently marked available in the registry.":
    "اس وقت رجسٹر میں کوئی پناہ گاہ دستیاب نہیں دکھائی گئی۔",
  "Nearest available rescue team": "قریب ترین دستیاب امدادی ٹیم",
  "No rescue team is currently marked available.":
    "اس وقت کوئی امدادی ٹیم دستیاب نہیں دکھائی گئی۔",
  "Your open reports": "آپ کی زیر التوا اطلاعات",
  "Still being worked. Track them under My Reports.":
    "ابھی کام جاری ہے۔ میری اطلاعات میں انہیں دیکھیں۔",
  "Nothing outstanding from you right now.": "اس وقت آپ کا کچھ زیر التوا نہیں۔",
  "None listed": "کوئی نہیں",
  "capacity {n}": "گنجائش {n}",
  "No active alerts nearby.": "قریب کوئی فعال انتباہ نہیں۔",
  "You haven't submitted any reports yet.": "آپ نے ابھی تک کوئی اطلاع نہیں بھیجی۔",

  low: "کم",
  medium: "درمیانی",
  high: "زیادہ",
  critical: "نازک",
  advisory: "ہدایت",
  watch: "نگرانی",
  warning: "انتباہ",
  severe: "شدید",
  open: "کھلی",
  assigned: "تفویض شدہ",
  resolved: "حل شدہ",
  available: "دستیاب",
  full: "بھری ہوئی",
  dispatched: "روانہ",
  shelter: "پناہ گاہ",
  "rescue team": "امدادی ٹیم",
  "supply stock": "رسد ذخیرہ",
  Open: "کھلی",
  Full: "بھری ہوئی",
  "Out on a call": "کام پر گئی ہوئی",

  "National Emergency Number": "قومی ہنگامی نمبر",
  Police: "پولیس",
  Fire: "فائر بریگیڈ",
  Ambulance: "ایمبولینس",
  "NDMA Disaster Management Helpline": "این ڈی ایم اے آفات انتظام ہیلپ لائن",
  "Women's Helpline": "خواتین ہیلپ لائن",
  "Call {name} on {number}": "{name} کو {number} پر کال کریں",

  Close: "بند کریں",
  Change: "تبدیل کریں",
  "Change language": "زبان تبدیل کریں",
  "Choose your language": "اپنی زبان منتخب کریں",

  // Strings the citizen web view has and the app does not.
  "Sign out": "سائن آؤٹ",
  "Try again": "دوبارہ کوشش کریں",
  "Submitting…": "بھیجا جا رہا ہے…",
  "Hide place list": "جگہوں کی فہرست چھپائیں",
  "Attached photo preview": "منسلک تصویر کا پیش منظر",
  "Search for your city or district": "اپنا شہر یا ضلع تلاش کریں",
  "Search {cities} cities, {districts} districts…":
    "{cities} شہر، {districts} اضلاع میں تلاش کریں…",
  "Filter {n} towns…": "{n} قصبے چھانٹیں…",
  "Location not available yet — allow location access and try again.":
    "مقام ابھی دستیاب نہیں — مقام کی اجازت دیں اور دوبارہ کوشش کریں۔",
  "Set your location first — use the readout above.":
    "پہلے اپنا مقام متعین کریں — اوپر دی گئی تفصیل استعمال کریں۔",
  "Report submitted. Authorities have been notified.":
    "اطلاع بھیج دی گئی۔ حکام کو آگاہ کر دیا گیا ہے۔",
  "Official warnings near you, updated continuously":
    "آپ کے قریب سرکاری انتباہات، مسلسل تازہ ہوتے ہیں",
  "Nearest shelters and resources on the map": "نقشے پر قریب ترین پناہ گاہیں اور وسائل",
  "Fire, police, ambulance, disaster helplines":
    "فائر بریگیڈ، پولیس، ایمبولینس، آفات ہیلپ لائنیں",
  "This site is blocked from using your location.":
    "اس سائٹ کو آپ کا مقام استعمال کرنے سے روکا گیا ہے۔",
  "Allow location for this site in your browser settings, then try again — or just name your place below.":
    "اپنے براؤزر کی ترتیبات میں اس سائٹ کے لیے مقام کی اجازت دیں، پھر دوبارہ کوشش کریں — یا نیچے اپنی جگہ کا نام دے دیں۔",
  "Your device didn't return a location in time.": "آپ کے آلے نے وقت پر مقام نہیں بتایا۔",
  "Moving outdoors usually helps, or name your place below.":
    "کھلی جگہ پر جانے سے عام طور پر مدد ملتی ہے، یا نیچے اپنی جگہ کا نام دیں۔",
  "Your device couldn't determine a location.": "آپ کا آلہ مقام کا تعین نہ کر سکا۔",
  "Common on a desktop with no GPS, and on a phone with Location Services switched off. Name your place below instead.":
    "بغیر جی پی ایس کے کمپیوٹر پر اور مقام کی خدمات بند فون پر یہ عام ہے۔ اس کے بجائے نیچے اپنی جگہ کا نام دیں۔",
  "This browser doesn't support location lookup.":
    "یہ براؤزر مقام معلوم کرنے کی سہولت نہیں رکھتا۔",
  "Name your place below instead.": "اس کے بجائے نیچے اپنی جگہ کا نام دیں۔",
  "This page is not on a secure (https) connection, so the browser will not share your location.":
    "یہ صفحہ محفوظ (https) کنکشن پر نہیں، اس لیے براؤزر آپ کا مقام شیئر نہیں کرے گا۔",
  "Open the deployed https site, or name your place below.":
    "https سائٹ کھولیں، یا نیچے اپنی جگہ کا نام دیں۔",

  // Strings the citizen web view has and the app does not.
  "Hospitals": "ہسپتال",
  "Police stations": "پولیس اسٹیشن",
  "Fire stations": "فائر اسٹیشن",
  "Zoom in to see facilities": "سہولیات دیکھنے کے لیے زوم کریں",
  "None nearby": "قریب کچھ نہیں",
  "Showing {shown} of {total}": "{total} میں سے {shown} دکھائے جا رہے ہیں",
  "{n} nearby": "قریب {n}",
  "Could not load facilities": "سہولیات لوڈ نہیں ہو سکیں",
};
